import { getCardImageUrl } from './helpers';

// Cups (36-49), Swords (50-63), Pentacles (64-77)
export const minorArcanaCards = [
  // CUPS (36-49)
  {
    slug: 'ace-of-cups',
    name: 'Ace of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 1,
    sequenceIndex: 36,
    imageUrl: getCardImageUrl('Cups', 'cups', 1),
    keywords: JSON.stringify(['new love', 'compassion', 'emotional fulfillment', 'creativity']),
    summary: 'New beginnings in love, compassion, and emotional fulfillment.',
    uprightMeaning: 'The Ace of Cups represents love, new relationships, compassion, and creativity.',
    reversedMeaning: 'Emotional overwhelm or blocked feelings.',
  },
  {
    slug: 'two-of-cups',
    name: 'Two of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 2,
    sequenceIndex: 37,
    imageUrl: getCardImageUrl('Cups', 'cups', 2),
    keywords: JSON.stringify(['partnerships', 'mutual attraction', 'harmonious relationships', 'unity']),
    summary: 'Partnerships, mutual attraction, and harmonious relationships.',
    uprightMeaning: 'The Two of Cups represents unified love, partnership, and mutual attraction.',
    reversedMeaning: 'Co-dependency or imbalance in relationships.',
  },
  {
    slug: 'three-of-cups',
    name: 'Three of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 3,
    sequenceIndex: 38,
    imageUrl: getCardImageUrl('Cups', 'cups', 3),
    keywords: JSON.stringify(['celebration', 'friendship', 'community', 'joy']),
    summary: 'Celebration, friendship, and community support.',
    uprightMeaning: 'The Three of Cups represents celebration, friendship, creativity, and collaborations.',
    reversedMeaning: 'Excessive partying or gossip.',
  },
  {
    slug: 'four-of-cups',
    name: 'Four of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 4,
    sequenceIndex: 39,
    imageUrl: getCardImageUrl('Cups', 'cups', 4),
    keywords: JSON.stringify(['contemplation', 'reevaluation', 'introspection', 'apathy']),
    summary: 'Contemplation, reevaluation, and introspection.',
    uprightMeaning: 'The Four of Cups represents meditation, contemplation, and reevaluation.',
    reversedMeaning: 'Apathy, discontent, or missed opportunities.',
  },
  {
    slug: 'five-of-cups',
    name: 'Five of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 5,
    sequenceIndex: 40,
    imageUrl: getCardImageUrl('Cups', 'cups', 5),
    keywords: JSON.stringify(['loss', 'grief', 'regret', 'disappointment']),
    summary: 'Loss, grief, and focusing on the negative.',
    uprightMeaning: 'The Five of Cups represents regret, failure, disappointment, and pessimism.',
    reversedMeaning: 'Inability to move on or dwelling on past mistakes.',
  },
  {
    slug: 'six-of-cups',
    name: 'Six of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 6,
    sequenceIndex: 41,
    imageUrl: getCardImageUrl('Cups', 'cups', 6),
    keywords: JSON.stringify(['nostalgia', 'childhood memories', 'innocence', 'reunion']),
    summary: 'Nostalgia, childhood memories, and innocence.',
    uprightMeaning: 'The Six of Cups represents revisiting the past, childhood memories, and innocence.',
    reversedMeaning: 'Living in the past or refusing to grow up.',
  },
  {
    slug: 'seven-of-cups',
    name: 'Seven of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 7,
    sequenceIndex: 42,
    imageUrl: getCardImageUrl('Cups', 'cups', 7),
    keywords: JSON.stringify(['choices', 'imagination', 'wishful thinking', 'illusion']),
    summary: 'Choices, imagination, and wishful thinking.',
    uprightMeaning: 'The Seven of Cups represents opportunities, choices, wishful thinking, and illusion.',
    reversedMeaning: 'Illusion, temptation, or lack of focus.',
  },
  {
    slug: 'eight-of-cups',
    name: 'Eight of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 8,
    sequenceIndex: 43,
    imageUrl: getCardImageUrl('Cups', 'cups', 8),
    keywords: JSON.stringify(['walking away', 'seeking deeper meaning', 'introspection', 'withdrawal']),
    summary: 'Walking away, seeking deeper meaning, and introspection.',
    uprightMeaning: 'The Eight of Cups represents disappointment, abandonment, withdrawal, and escapism.',
    reversedMeaning: 'Avoidance or escapism.',
  },
  {
    slug: 'nine-of-cups',
    name: 'Nine of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 9,
    sequenceIndex: 44,
    imageUrl: getCardImageUrl('Cups', 'cups', 9),
    keywords: JSON.stringify(['contentment', 'satisfaction', 'emotional fulfillment', 'wishes granted']),
    summary: 'Contentment, satisfaction, and emotional fulfillment.',
    uprightMeaning: 'The Nine of Cups represents contentment, satisfaction, and emotional stability.',
    reversedMeaning: 'Complacency or overindulgence.',
  },
  {
    slug: 'ten-of-cups',
    name: 'Ten of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 10,
    sequenceIndex: 45,
    imageUrl: getCardImageUrl('Cups', 'cups', 10),
    keywords: JSON.stringify(['harmony', 'family bliss', 'lasting happiness', 'emotional fulfillment']),
    summary: 'Harmony, family bliss, and lasting happiness.',
    uprightMeaning: 'The Ten of Cups represents domestic harmony, happiness, and alignment.',
    reversedMeaning: 'Unrealistic expectations or superficial peace.',
  },
  {
    slug: 'page-of-cups',
    name: 'Page of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 11,
    sequenceIndex: 46,
    imageUrl: getCardImageUrl('Cups', 'cups', 11),
    keywords: JSON.stringify(['creative beginnings', 'emotional openness', 'curiosity', 'intuition']),
    summary: 'Creative beginnings, emotional openness, and curiosity.',
    uprightMeaning: 'The Page of Cups represents creative opportunities, intuitive messages, and curiosity.',
    reversedMeaning: 'Emotional immaturity or escapism.',
  },
  {
    slug: 'knight-of-cups',
    name: 'Knight of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 12,
    sequenceIndex: 47,
    imageUrl: getCardImageUrl('Cups', 'cups', 12),
    keywords: JSON.stringify(['romantic pursuit', 'idealism', 'following heart', 'charm']),
    summary: 'Romantic pursuit, idealism, and following one\'s heart.',
    uprightMeaning: 'The Knight of Cups represents romance, charm, imagination, and beauty.',
    reversedMeaning: 'Unrealistic ideals or fickleness.',
  },
  {
    slug: 'queen-of-cups',
    name: 'Queen of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 13,
    sequenceIndex: 48,
    imageUrl: getCardImageUrl('Cups', 'cups', 13),
    keywords: JSON.stringify(['compassion', 'intuition', 'nurturing', 'emotional maturity']),
    summary: 'Compassion, intuition, and nurturing.',
    uprightMeaning: 'The Queen of Cups represents compassion, calm, comfort, and intuition.',
    reversedMeaning: 'Overemotional or martyrdom.',
  },
  {
    slug: 'king-of-cups',
    name: 'King of Cups',
    arcanaType: 'minor' as const,
    suit: 'cups' as const,
    number: 14,
    sequenceIndex: 49,
    imageUrl: getCardImageUrl('Cups', 'cups', 14),
    keywords: JSON.stringify(['emotional balance', 'diplomacy', 'generosity', 'wisdom']),
    summary: 'Emotional balance, diplomacy, and generosity.',
    uprightMeaning: 'The King of Cups represents diplomacy, emotional balance, devotion, and counsellor.',
    reversedMeaning: 'Emotional suppression or manipulation.',
  },

  // SWORDS (50-63)
  {
    slug: 'ace-of-swords',
    name: 'Ace of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 1,
    sequenceIndex: 50,
    imageUrl: getCardImageUrl('Swords', 'swords', 1),
    keywords: JSON.stringify(['breakthroughs', 'clarity', 'sharp mind', 'new ideas']),
    summary: 'Breakthroughs, clarity, and sharp mind.',
    uprightMeaning: 'The Ace of Swords represents breakthroughs, new ideas, mental clarity, and success.',
    reversedMeaning: 'Confusion or miscommunication.',
  },
  {
    slug: 'two-of-swords',
    name: 'Two of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 2,
    sequenceIndex: 51,
    imageUrl: getCardImageUrl('Swords', 'swords', 2),
    keywords: JSON.stringify(['indecision', 'stalemate', 'difficult choices', 'avoidance']),
    summary: 'Indecision, stalemate, and difficult choices.',
    uprightMeaning: 'The Two of Swords represents difficult decisions, weighing options, and stalemate.',
    reversedMeaning: 'Avoidance or denial.',
  },
  {
    slug: 'three-of-swords',
    name: 'Three of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 3,
    sequenceIndex: 52,
    imageUrl: getCardImageUrl('Swords', 'swords', 3),
    keywords: JSON.stringify(['heartbreak', 'sorrow', 'emotional pain', 'grief']),
    summary: 'Heartbreak, sorrow, and emotional pain.',
    uprightMeaning: 'The Three of Swords represents heartbreak, emotional pain, sorrow, and grief.',
    reversedMeaning: 'Holding onto pain or resentment.',
  },
  {
    slug: 'four-of-swords',
    name: 'Four of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 4,
    sequenceIndex: 53,
    imageUrl: getCardImageUrl('Swords', 'swords', 4),
    keywords: JSON.stringify(['rest', 'contemplation', 'recovery', 'meditation']),
    summary: 'Rest, contemplation, and recovery.',
    uprightMeaning: 'The Four of Swords represents rest, relaxation, meditation, and contemplation.',
    reversedMeaning: 'Burnout or stagnation.',
  },
  {
    slug: 'five-of-swords',
    name: 'Five of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 5,
    sequenceIndex: 54,
    imageUrl: getCardImageUrl('Swords', 'swords', 5),
    keywords: JSON.stringify(['conflict', 'betrayal', 'hollow victory', 'defeat']),
    summary: 'Conflict, betrayal, and hollow victory.',
    uprightMeaning: 'The Five of Swords represents conflict, disagreements, competition, and defeat.',
    reversedMeaning: 'Selfishness or unnecessary aggression.',
  },
  {
    slug: 'six-of-swords',
    name: 'Six of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 6,
    sequenceIndex: 55,
    imageUrl: getCardImageUrl('Swords', 'swords', 6),
    keywords: JSON.stringify(['transition', 'letting go', 'moving forward', 'change']),
    summary: 'Transition, letting go, and moving forward.',
    uprightMeaning: 'The Six of Swords represents transition, change, rite of passage, and releasing baggage.',
    reversedMeaning: 'Resistance to change or unfinished business.',
  },
  {
    slug: 'seven-of-swords',
    name: 'Seven of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 7,
    sequenceIndex: 56,
    imageUrl: getCardImageUrl('Swords', 'swords', 7),
    keywords: JSON.stringify(['strategy', 'deception', 'cunning', 'trickery']),
    summary: 'Strategy, deception, and cunning.',
    uprightMeaning: 'The Seven of Swords represents betrayal, deception, getting away with something, and stealth.',
    reversedMeaning: 'Dishonesty or self-deception.',
  },
  {
    slug: 'eight-of-swords',
    name: 'Eight of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 8,
    sequenceIndex: 57,
    imageUrl: getCardImageUrl('Swords', 'swords', 8),
    keywords: JSON.stringify(['feeling trapped', 'self-imposed limitations', 'negative thoughts', 'isolation']),
    summary: 'Feeling trapped, self-imposed limitations.',
    uprightMeaning: 'The Eight of Swords represents negative thoughts, self-imposed restriction, and imprisonment.',
    reversedMeaning: 'Victim mindset or helplessness.',
  },
  {
    slug: 'nine-of-swords',
    name: 'Nine of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 9,
    sequenceIndex: 58,
    imageUrl: getCardImageUrl('Swords', 'swords', 9),
    keywords: JSON.stringify(['anxiety', 'fear', 'nightmares', 'worry']),
    summary: 'Anxiety, fear, and nightmares.',
    uprightMeaning: 'The Nine of Swords represents anxiety, worry, fear, depression, and nightmares.',
    reversedMeaning: 'Overthinking or overwhelming stress.',
  },
  {
    slug: 'ten-of-swords',
    name: 'Ten of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 10,
    sequenceIndex: 59,
    imageUrl: getCardImageUrl('Swords', 'swords', 10),
    keywords: JSON.stringify(['endings', 'collapse', 'surrender', 'rock bottom']),
    summary: 'Endings, collapse, and surrender.',
    uprightMeaning: 'The Ten of Swords represents painful endings, deep wounds, betrayal, and loss.',
    reversedMeaning: 'Overkill, melodrama, or feeling like a victim.',
  },
  {
    slug: 'page-of-swords',
    name: 'Page of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 11,
    sequenceIndex: 60,
    imageUrl: getCardImageUrl('Swords', 'swords', 11),
    keywords: JSON.stringify(['curiosity', 'new ideas', 'thirst for knowledge', 'vigilance']),
    summary: 'Curiosity, new ideas, and thirst for knowledge.',
    uprightMeaning: 'The Page of Swords represents new ideas, curiosity, thirst for knowledge, and vigilance.',
    reversedMeaning: 'Gossip, paranoia, or misinformation.',
  },
  {
    slug: 'knight-of-swords',
    name: 'Knight of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 12,
    sequenceIndex: 61,
    imageUrl: getCardImageUrl('Swords', 'swords', 12),
    keywords: JSON.stringify(['ambition', 'quick thinking', 'action', 'assertiveness']),
    summary: 'Ambition, quick thinking, and action.',
    uprightMeaning: 'The Knight of Swords represents ambitious, action-oriented, driven to succeed, and fast-thinking.',
    reversedMeaning: 'Impulsiveness or recklessness.',
  },
  {
    slug: 'queen-of-swords',
    name: 'Queen of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 13,
    sequenceIndex: 62,
    imageUrl: getCardImageUrl('Swords', 'swords', 13),
    keywords: JSON.stringify(['intellect', 'clear communication', 'independence', 'unbiased judgment']),
    summary: 'Intellect, clear communication, and independence.',
    uprightMeaning: 'The Queen of Swords represents independent, unbiased judgement, clear boundaries, and direct communication.',
    reversedMeaning: 'Coldness or emotional detachment.',
  },
  {
    slug: 'king-of-swords',
    name: 'King of Swords',
    arcanaType: 'minor' as const,
    suit: 'swords' as const,
    number: 14,
    sequenceIndex: 63,
    imageUrl: getCardImageUrl('Swords', 'swords', 14),
    keywords: JSON.stringify(['authority', 'truth', 'mental clarity', 'ethical power']),
    summary: 'Authority, truth, and mental clarity.',
    uprightMeaning: 'The King of Swords represents mental clarity, intellectual power, authority, and truth.',
    reversedMeaning: 'Manipulation or rigid thinking.',
  },

  // PENTACLES (64-77)
  {
    slug: 'ace-of-pentacles',
    name: 'Ace of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 1,
    sequenceIndex: 64,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 1),
    keywords: JSON.stringify(['new financial beginnings', 'prosperity', 'opportunity', 'manifestation']),
    summary: 'New financial beginnings, prosperity, and opportunity.',
    uprightMeaning: 'The Ace of Pentacles represents new financial opportunity, manifestation, and abundance.',
    reversedMeaning: 'Missed chances, greed, or instability.',
  },
  {
    slug: 'two-of-pentacles',
    name: 'Two of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 2,
    sequenceIndex: 65,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 2),
    keywords: JSON.stringify(['balance', 'adaptability', 'time management', 'prioritization']),
    summary: 'Balance, adaptability, and time management.',
    uprightMeaning: 'The Two of Pentacles represents multiple priorities, time management, and adaptability.',
    reversedMeaning: 'Overcommitment or financial stress.',
  },
  {
    slug: 'three-of-pentacles',
    name: 'Three of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 3,
    sequenceIndex: 66,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 3),
    keywords: JSON.stringify(['teamwork', 'collaboration', 'craftsmanship', 'learning']),
    summary: 'Teamwork, collaboration, and craftsmanship.',
    uprightMeaning: 'The Three of Pentacles represents teamwork, collaboration, learning, and implementation.',
    reversedMeaning: 'Lack of teamwork or poor planning.',
  },
  {
    slug: 'four-of-pentacles',
    name: 'Four of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 4,
    sequenceIndex: 67,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 4),
    keywords: JSON.stringify(['saving', 'security', 'control', 'conservation']),
    summary: 'Saving, security, and control.',
    uprightMeaning: 'The Four of Pentacles represents saving money, security, conservatism, and scarcity.',
    reversedMeaning: 'Greed or fear of financial loss.',
  },
  {
    slug: 'five-of-pentacles',
    name: 'Five of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 5,
    sequenceIndex: 68,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 5),
    keywords: JSON.stringify(['financial loss', 'hardship', 'struggle', 'isolation']),
    summary: 'Financial loss, hardship, and struggle.',
    uprightMeaning: 'The Five of Pentacles represents financial loss, poverty, lack mindset, and isolation.',
    reversedMeaning: 'Despair, isolation, or helplessness.',
  },
  {
    slug: 'six-of-pentacles',
    name: 'Six of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 6,
    sequenceIndex: 69,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 6),
    keywords: JSON.stringify(['generosity', 'charity', 'financial balance', 'giving']),
    summary: 'Generosity, charity, and financial balance.',
    uprightMeaning: 'The Six of Pentacles represents generosity, charity, giving, and prosperity.',
    reversedMeaning: 'Power imbalance or strings attached.',
  },
  {
    slug: 'seven-of-pentacles',
    name: 'Seven of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 7,
    sequenceIndex: 70,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 7),
    keywords: JSON.stringify(['patience', 'long-term investment', 'growth', 'perseverance']),
    summary: 'Patience, long-term investment, and growth.',
    uprightMeaning: 'The Seven of Pentacles represents long-term view, sustainable results, and perseverance.',
    reversedMeaning: 'Impatience, lack of progress, or wasted effort.',
  },
  {
    slug: 'eight-of-pentacles',
    name: 'Eight of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 8,
    sequenceIndex: 71,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 8),
    keywords: JSON.stringify(['mastery', 'skill development', 'diligence', 'craftsmanship']),
    summary: 'Mastery, skill development, and diligence.',
    uprightMeaning: 'The Eight of Pentacles represents apprenticeship, repetitive tasks, mastery, and skill development.',
    reversedMeaning: 'Perfectionism or overworking.',
  },
  {
    slug: 'nine-of-pentacles',
    name: 'Nine of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 9,
    sequenceIndex: 72,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 9),
    keywords: JSON.stringify(['independence', 'luxury', 'self-sufficiency', 'abundance']),
    summary: 'Independence, luxury, and self-sufficiency.',
    uprightMeaning: 'The Nine of Pentacles represents abundance, luxury, self-sufficiency, and financial independence.',
    reversedMeaning: 'Materialism or isolation.',
  },
  {
    slug: 'ten-of-pentacles',
    name: 'Ten of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 10,
    sequenceIndex: 73,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 10),
    keywords: JSON.stringify(['legacy', 'financial security', 'long-term success', 'tradition']),
    summary: 'Legacy, financial security, and long-term success.',
    uprightMeaning: 'The Ten of Pentacles represents wealth, financial security, family, and long-term success.',
    reversedMeaning: 'Family conflicts over money or business.',
  },
  {
    slug: 'page-of-pentacles',
    name: 'Page of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 11,
    sequenceIndex: 74,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 11),
    keywords: JSON.stringify(['ambition', 'learning', 'new opportunities', 'manifestation']),
    summary: 'Ambition, learning, and new opportunities.',
    uprightMeaning: 'The Page of Pentacles represents manifestation, financial opportunity, new job, and skill development.',
    reversedMeaning: 'Lack of follow-through or procrastination.',
  },
  {
    slug: 'knight-of-pentacles',
    name: 'Knight of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 12,
    sequenceIndex: 75,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 12),
    keywords: JSON.stringify(['hard work', 'responsibility', 'reliability', 'routine']),
    summary: 'Hard work, responsibility, and reliability.',
    uprightMeaning: 'The Knight of Pentacles represents hard work, productivity, routine, and conservatism.',
    reversedMeaning: 'Stubbornness or resistance to change.',
  },
  {
    slug: 'queen-of-pentacles',
    name: 'Queen of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 13,
    sequenceIndex: 76,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 13),
    keywords: JSON.stringify(['nurturing', 'financial security', 'practicality', 'work-life balance']),
    summary: 'Nurturing, financial security, and practicality.',
    uprightMeaning: 'The Queen of Pentacles represents practical, homely, motherly, and down-to-earth.',
    reversedMeaning: 'Overly controlling or neglecting self-care.',
  },
  {
    slug: 'king-of-pentacles',
    name: 'King of Pentacles',
    arcanaType: 'minor' as const,
    suit: 'pentacles' as const,
    number: 14,
    sequenceIndex: 77,
    imageUrl: getCardImageUrl('Pentacles', 'pentacles', 14),
    keywords: JSON.stringify(['success', 'wealth', 'stability', 'abundance']),
    summary: 'Success, wealth, and stability.',
    uprightMeaning: 'The King of Pentacles represents wealth, business, leadership, security, and discipline.',
    reversedMeaning: 'Greed, corruption, or being controlling.',
  },
];
