import { getCardImageUrl, generateSlug } from './helpers';
import { minorArcanaCards } from './cards-minor';

const majorArcanaCards = [
  // Major Arcana (0-21)
  {
    slug: 'the-fool',
    name: 'The Fool',
    arcanaType: 'major' as const,
    suit: null,
    number: 0,
    sequenceIndex: 0,
    imageUrl: getCardImageUrl('The-Fool', null, 0),
    keywords: JSON.stringify(['new beginnings', 'spontaneity', 'free spirit', 'leap of faith']),
    summary: 'New beginnings, spontaneity, and a free spirit.',
    uprightMeaning: 'The Fool represents new beginnings, having faith in the future, being inexperienced, not knowing what to expect, having beginner\'s luck, improvisation and believing in the universe.',
    reversedMeaning: 'Recklessness or naivety.',
  },
  {
    slug: 'the-magician',
    name: 'The Magician',
    arcanaType: 'major' as const,
    suit: null,
    number: 1,
    sequenceIndex: 1,
    imageUrl: getCardImageUrl('The-Magician', null, 1),
    keywords: JSON.stringify(['manifestation', 'resourcefulness', 'inspired action', 'power']),
    summary: 'Manifestation, resourcefulness, and inspired action.',
    uprightMeaning: 'The Magician is the master of manifestation. He represents inspired action, resourcefulness, power, and the ability to manifest one\'s desires.',
    reversedMeaning: 'Manipulation or illusion.',
  },
  {
    slug: 'the-high-priestess',
    name: 'The High Priestess',
    arcanaType: 'major' as const,
    suit: null,
    number: 2,
    sequenceIndex: 2,
    imageUrl: getCardImageUrl('The-High-Priestess', null, 2),
    keywords: JSON.stringify(['intuition', 'subconscious', 'wisdom', 'sacred knowledge']),
    summary: 'Intuition, subconscious mind, and wisdom.',
    uprightMeaning: 'The High Priestess represents intuition, sacred knowledge, divine feminine, and the subconscious mind.',
    reversedMeaning: 'Secrets or disconnect from inner knowing.',
  },
  {
    slug: 'the-empress',
    name: 'The Empress',
    arcanaType: 'major' as const,
    suit: null,
    number: 3,
    sequenceIndex: 3,
    imageUrl: getCardImageUrl('The-Empress', null, 3),
    keywords: JSON.stringify(['nurturing', 'abundance', 'creativity', 'nature']),
    summary: 'Nurturing, abundance, and creativity.',
    uprightMeaning: 'The Empress represents nurturing, abundance, nature, fertility, and the divine feminine.',
    reversedMeaning: 'Overindulgence or dependence.',
  },
  {
    slug: 'the-emperor',
    name: 'The Emperor',
    arcanaType: 'major' as const,
    suit: null,
    number: 4,
    sequenceIndex: 4,
    imageUrl: getCardImageUrl('The-Emperor', null, 4),
    keywords: JSON.stringify(['authority', 'structure', 'leadership', 'stability']),
    summary: 'Authority, structure, and leadership.',
    uprightMeaning: 'The Emperor represents authority, establishment, structure, and a father figure.',
    reversedMeaning: 'Tyranny or rigidity.',
  },
  {
    slug: 'the-hierophant',
    name: 'The Hierophant',
    arcanaType: 'major' as const,
    suit: null,
    number: 5,
    sequenceIndex: 5,
    imageUrl: getCardImageUrl('The-Hierophant', null, 5),
    keywords: JSON.stringify(['tradition', 'spiritual wisdom', 'learning', 'institutions']),
    summary: 'Tradition, spiritual wisdom, and learning.',
    uprightMeaning: 'The Hierophant represents spiritual wisdom, religious beliefs, conformity, tradition, and institutions.',
    reversedMeaning: 'Dogmatism or blind obedience.',
  },
  {
    slug: 'the-lovers',
    name: 'The Lovers',
    arcanaType: 'major' as const,
    suit: null,
    number: 6,
    sequenceIndex: 6,
    imageUrl: getCardImageUrl('The-Lovers', null, 6),
    keywords: JSON.stringify(['love', 'harmony', 'relationships', 'values alignment']),
    summary: 'Love, harmony, and relationships.',
    uprightMeaning: 'The Lovers represent love, harmony, relationships, values alignment, and choices.',
    reversedMeaning: 'Disharmony or misalignment in values.',
  },
  {
    slug: 'the-chariot',
    name: 'The Chariot',
    arcanaType: 'major' as const,
    suit: null,
    number: 7,
    sequenceIndex: 7,
    imageUrl: getCardImageUrl('The-Chariot', null, 7),
    keywords: JSON.stringify(['willpower', 'determination', 'success', 'control']),
    summary: 'Willpower, determination, and success.',
    uprightMeaning: 'The Chariot represents control, willpower, success, action, and determination.',
    reversedMeaning: 'Lack of direction or aggression.',
  },
  {
    slug: 'strength',
    name: 'Strength',
    arcanaType: 'major' as const,
    suit: null,
    number: 8,
    sequenceIndex: 8,
    imageUrl: getCardImageUrl('Strength', null, 8),
    keywords: JSON.stringify(['courage', 'patience', 'inner strength', 'compassion']),
    summary: 'Courage, patience, and inner strength.',
    uprightMeaning: 'Strength represents inner strength, bravery, compassion, focus, and overcoming challenges.',
    reversedMeaning: 'Self-doubt or suppressed emotions.',
  },
  {
    slug: 'the-hermit',
    name: 'The Hermit',
    arcanaType: 'major' as const,
    suit: null,
    number: 9,
    sequenceIndex: 9,
    imageUrl: getCardImageUrl('The-Hermit', null, 9),
    keywords: JSON.stringify(['introspection', 'solitude', 'inner guidance', 'wisdom']),
    summary: 'Introspection, solitude, and inner guidance.',
    uprightMeaning: 'The Hermit represents soul-searching, introspection, being alone, and inner guidance.',
    reversedMeaning: 'Isolation or withdrawal.',
  },
  {
    slug: 'wheel-of-fortune',
    name: 'Wheel of Fortune',
    arcanaType: 'major' as const,
    suit: null,
    number: 10,
    sequenceIndex: 10,
    imageUrl: getCardImageUrl('Wheel-of-Fortune', null, 10),
    keywords: JSON.stringify(['cycles', 'luck', 'destiny', 'turning point']),
    summary: 'Cycles, luck, and destiny.',
    uprightMeaning: 'Wheel of Fortune represents good luck, karma, life cycles, destiny, and a turning point.',
    reversedMeaning: 'Lack of control or external forces dictating fate.',
  },
  {
    slug: 'justice',
    name: 'Justice',
    arcanaType: 'major' as const,
    suit: null,
    number: 11,
    sequenceIndex: 11,
    imageUrl: getCardImageUrl('Justice', null, 11),
    keywords: JSON.stringify(['fairness', 'truth', 'law', 'accountability']),
    summary: 'Fairness, truth, and law.',
    uprightMeaning: 'Justice represents fairness, truth, cause and effect, and law.',
    reversedMeaning: 'Lack of accountability or unfairness.',
  },
  {
    slug: 'the-hanged-man',
    name: 'The Hanged Man',
    arcanaType: 'major' as const,
    suit: null,
    number: 12,
    sequenceIndex: 12,
    imageUrl: getCardImageUrl('The-Hanged-Man', null, 12),
    keywords: JSON.stringify(['surrender', 'new perspective', 'letting go', 'pause']),
    summary: 'Surrender, new perspective, and letting go.',
    uprightMeaning: 'The Hanged Man represents pause, surrender, letting go, and new perspectives.',
    reversedMeaning: 'Resistance to change or stagnation.',
  },
  {
    slug: 'death',
    name: 'Death',
    arcanaType: 'major' as const,
    suit: null,
    number: 13,
    sequenceIndex: 13,
    imageUrl: getCardImageUrl('Death', null, 13),
    keywords: JSON.stringify(['transformation', 'endings', 'new beginnings', 'transition']),
    summary: 'Transformation, endings, and new beginnings.',
    uprightMeaning: 'Death represents endings, change, transformation, and transition.',
    reversedMeaning: 'Fear of change or resistance to transformation.',
  },
  {
    slug: 'temperance',
    name: 'Temperance',
    arcanaType: 'major' as const,
    suit: null,
    number: 14,
    sequenceIndex: 14,
    imageUrl: getCardImageUrl('Temperance', null, 14),
    keywords: JSON.stringify(['balance', 'moderation', 'patience', 'harmony']),
    summary: 'Balance, moderation, and patience.',
    uprightMeaning: 'Temperance represents balance, moderation, patience, and finding meaning.',
    reversedMeaning: 'Extremism or lack of harmony.',
  },
  {
    slug: 'the-devil',
    name: 'The Devil',
    arcanaType: 'major' as const,
    suit: null,
    number: 15,
    sequenceIndex: 15,
    imageUrl: getCardImageUrl('The-Devil', null, 15),
    keywords: JSON.stringify(['materialism', 'addiction', 'shadow work', 'bondage']),
    summary: 'Materialism, addiction, and shadow work.',
    uprightMeaning: 'The Devil represents shadow self, attachment, addiction, restriction, and sexuality.',
    reversedMeaning: 'Entrapment or lack of self-control.',
  },
  {
    slug: 'the-tower',
    name: 'The Tower',
    arcanaType: 'major' as const,
    suit: null,
    number: 16,
    sequenceIndex: 16,
    imageUrl: getCardImageUrl('The-Tower', null, 16),
    keywords: JSON.stringify(['sudden upheaval', 'destruction', 'revelation', 'awakening']),
    summary: 'Sudden upheaval, destruction, and revelation.',
    uprightMeaning: 'The Tower represents sudden change, upheaval, chaos, revelation, and awakening.',
    reversedMeaning: 'Fear of change or clinging to the past.',
  },
  {
    slug: 'the-star',
    name: 'The Star',
    arcanaType: 'major' as const,
    suit: null,
    number: 17,
    sequenceIndex: 17,
    imageUrl: getCardImageUrl('The-Star', null, 17),
    keywords: JSON.stringify(['hope', 'inspiration', 'renewal', 'serenity']),
    summary: 'Hope, inspiration, and renewal.',
    uprightMeaning: 'The Star represents hope, faith, purpose, renewal, and spirituality.',
    reversedMeaning: 'Despair or loss of faith.',
  },
  {
    slug: 'the-moon',
    name: 'The Moon',
    arcanaType: 'major' as const,
    suit: null,
    number: 18,
    sequenceIndex: 18,
    imageUrl: getCardImageUrl('The-Moon', null, 18),
    keywords: JSON.stringify(['illusion', 'intuition', 'subconscious fears', 'uncertainty']),
    summary: 'Illusion, intuition, and subconscious fears.',
    uprightMeaning: 'The Moon represents illusion, fear, anxiety, subconscious, and intuition.',
    reversedMeaning: 'Anxiety or deception.',
  },
  {
    slug: 'the-sun',
    name: 'The Sun',
    arcanaType: 'major' as const,
    suit: null,
    number: 19,
    sequenceIndex: 19,
    imageUrl: getCardImageUrl('The-Sun', null, 19),
    keywords: JSON.stringify(['joy', 'success', 'positivity', 'vitality']),
    summary: 'Joy, success, and positivity.',
    uprightMeaning: 'The Sun represents positivity, fun, warmth, success, and vitality.',
    reversedMeaning: 'Egoism or overconfidence.',
  },
  {
    slug: 'judgement',
    name: 'Judgement',
    arcanaType: 'major' as const,
    suit: null,
    number: 20,
    sequenceIndex: 20,
    imageUrl: getCardImageUrl('Judgement', null, 20),
    keywords: JSON.stringify(['awakening', 'reflection', 'renewal', 'inner calling']),
    summary: 'Awakening, reflection, and renewal.',
    uprightMeaning: 'Judgement represents judgement, rebirth, inner calling, and absolution.',
    reversedMeaning: 'Self-doubt or lack of forgiveness.',
  },
  {
    slug: 'the-world',
    name: 'The World',
    arcanaType: 'major' as const,
    suit: null,
    number: 21,
    sequenceIndex: 21,
    imageUrl: getCardImageUrl('The-World', null, 21),
    keywords: JSON.stringify(['completion', 'fulfillment', 'achievement', 'integration']),
    summary: 'Completion, fulfillment, and achievement.',
    uprightMeaning: 'The World represents completion, accomplishment, travel, and fulfillment.',
    reversedMeaning: 'Unfinished business or stagnation.',
  },

  // Wands (22-35)
  {
    slug: 'ace-of-wands',
    name: 'Ace of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 1,
    sequenceIndex: 22,
    imageUrl: getCardImageUrl('Wands', 'wands', 1),
    keywords: JSON.stringify(['new beginnings', 'inspiration', 'potential', 'creative spark']),
    summary: 'New beginnings, inspiration, and potential.',
    uprightMeaning: 'The Ace of Wands represents new beginnings, inspiration, creative spark, and growth.',
    reversedMeaning: 'Lack of direction or delays.',
  },
  {
    slug: 'two-of-wands',
    name: 'Two of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 2,
    sequenceIndex: 23,
    imageUrl: getCardImageUrl('Wands', 'wands', 2),
    keywords: JSON.stringify(['planning', 'decision-making', 'progress', 'discovery']),
    summary: 'Planning, decision-making, and progress.',
    uprightMeaning: 'The Two of Wands represents planning, making decisions, leaving home, and discovery.',
    reversedMeaning: 'Fear of the unknown or lack of planning.',
  },
  {
    slug: 'three-of-wands',
    name: 'Three of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 3,
    sequenceIndex: 24,
    imageUrl: getCardImageUrl('Wands', 'wands', 3),
    keywords: JSON.stringify(['expansion', 'foresight', 'opportunity', 'leadership']),
    summary: 'Expansion, foresight, and opportunity.',
    uprightMeaning: 'The Three of Wands represents expansion, foresight, overseas opportunities, and leadership.',
    reversedMeaning: 'Playing small or unexpected delays.',
  },
  {
    slug: 'four-of-wands',
    name: 'Four of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 4,
    sequenceIndex: 25,
    imageUrl: getCardImageUrl('Wands', 'wands', 4),
    keywords: JSON.stringify(['celebration', 'harmony', 'community', 'homecoming']),
    summary: 'Celebration, harmony, and community.',
    uprightMeaning: 'The Four of Wands represents celebration, joyful reunion, and relaxation.',
    reversedMeaning: 'Lack of communication or instability.',
  },
  {
    slug: 'five-of-wands',
    name: 'Five of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 5,
    sequenceIndex: 26,
    imageUrl: getCardImageUrl('Wands', 'wands', 5),
    keywords: JSON.stringify(['conflict', 'competition', 'challenges', 'disagreement']),
    summary: 'Conflict, competition, and challenges.',
    uprightMeaning: 'The Five of Wands represents conflict, disagreements, competition, and tension.',
    reversedMeaning: 'Avoidance or escalation of conflict.',
  },
  {
    slug: 'six-of-wands',
    name: 'Six of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 6,
    sequenceIndex: 27,
    imageUrl: getCardImageUrl('Wands', 'wands', 6),
    keywords: JSON.stringify(['victory', 'recognition', 'success', 'public acclaim']),
    summary: 'Victory, recognition, and success.',
    uprightMeaning: 'The Six of Wands represents public recognition, progress, and self-confidence.',
    reversedMeaning: 'Egotism or fall from grace.',
  },
  {
    slug: 'seven-of-wands',
    name: 'Seven of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 7,
    sequenceIndex: 28,
    imageUrl: getCardImageUrl('Wands', 'wands', 7),
    keywords: JSON.stringify(['perseverance', 'defense', 'maintaining control', 'challenge']),
    summary: 'Perseverance, defense, and maintaining control.',
    uprightMeaning: 'The Seven of Wands represents perseverance, defensive, maintaining control over a situation.',
    reversedMeaning: 'Exhaustion or being overwhelmed.',
  },
  {
    slug: 'eight-of-wands',
    name: 'Eight of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 8,
    sequenceIndex: 29,
    imageUrl: getCardImageUrl('Wands', 'wands', 8),
    keywords: JSON.stringify(['rapid action', 'movement', 'swift change', 'speed']),
    summary: 'Rapid action, movement, and swift change.',
    uprightMeaning: 'The Eight of Wands represents rapid action, movement, and swift change.',
    reversedMeaning: 'Hastiness or chaos.',
  },
  {
    slug: 'nine-of-wands',
    name: 'Nine of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 9,
    sequenceIndex: 30,
    imageUrl: getCardImageUrl('Wands', 'wands', 9),
    keywords: JSON.stringify(['resilience', 'courage', 'persistence', 'test of faith']),
    summary: 'Resilience, courage, and persistence.',
    uprightMeaning: 'The Nine of Wands represents resilience, courage, persistence, and test of faith.',
    reversedMeaning: 'Paranoia or defensiveness.',
  },
  {
    slug: 'ten-of-wands',
    name: 'Ten of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 10,
    sequenceIndex: 31,
    imageUrl: getCardImageUrl('Wands', 'wands', 10),
    keywords: JSON.stringify(['burden', 'responsibility', 'hard work', 'stress']),
    summary: 'Burden, responsibility, and hard work.',
    uprightMeaning: 'The Ten of Wands represents burden, extra responsibility, hard work, and completion.',
    reversedMeaning: 'Burnout or taking on too much.',
  },
  {
    slug: 'page-of-wands',
    name: 'Page of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 11,
    sequenceIndex: 32,
    imageUrl: getCardImageUrl('Wands', 'wands', 11),
    keywords: JSON.stringify(['enthusiasm', 'exploration', 'free spirit', 'discovery']),
    summary: 'Enthusiasm, exploration, and free spirit.',
    uprightMeaning: 'The Page of Wands represents enthusiasm, exploration, discovery, and free spirit.',
    reversedMeaning: 'Lack of direction or immaturity.',
  },
  {
    slug: 'knight-of-wands',
    name: 'Knight of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 12,
    sequenceIndex: 33,
    imageUrl: getCardImageUrl('Wands', 'wands', 12),
    keywords: JSON.stringify(['action', 'adventure', 'impulsiveness', 'energy']),
    summary: 'Action, adventure, and impulsiveness.',
    uprightMeaning: 'The Knight of Wands represents action, adventure, fearlessness, and energy.',
    reversedMeaning: 'Recklessness or impatience.',
  },
  {
    slug: 'queen-of-wands',
    name: 'Queen of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 13,
    sequenceIndex: 34,
    imageUrl: getCardImageUrl('Wands', 'wands', 13),
    keywords: JSON.stringify(['confidence', 'determination', 'social influence', 'charisma']),
    summary: 'Confidence, determination, and social influence.',
    uprightMeaning: 'The Queen of Wands represents courage, determination, joy, and confidence.',
    reversedMeaning: 'Jealousy or selfishness.',
  },
  {
    slug: 'king-of-wands',
    name: 'King of Wands',
    arcanaType: 'minor' as const,
    suit: 'wands' as const,
    number: 14,
    sequenceIndex: 35,
    imageUrl: getCardImageUrl('Wands', 'wands', 14),
    keywords: JSON.stringify(['natural-born leader', 'vision', 'entrepreneur', 'honour']),
    summary: 'Natural-born leader, vision, and entrepreneur.',
    uprightMeaning: 'The King of Wands represents natural-born leader, vision, entrepreneur, and honour.',
    reversedMeaning: 'Impulsiveness or ruthlessness.',
  },
];

// Export all 78 cards (22 Major + 14 Wands + 14 Cups + 14 Swords + 14 Pentacles)
export const cardsSeedData = [...majorArcanaCards, ...minorArcanaCards];

