import { generateSlug } from './helpers';

// Unique TED talks extracted from CSV files
// Note: Some talks appear multiple times across different cards
export const talksSeedData = [
  {
    slug: generateSlug('Bryan Stevenson We Need to Talk About an Injustice'),
    title: 'We Need to Talk About an Injustice',
    speakerName: 'Bryan Stevenson',
    tedUrl: 'https://www.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice',
    description: 'Bryan Stevenson presents the statistics and stories of our racially biased justice system.',
    durationSeconds: 1422,
    eventName: 'TED',
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/1798fc73-fe80-474c-a63b-4f427ab241b7/BryanStevenson_2012-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'c2tOp7OxyQ8',
  },
  {
    slug: generateSlug('Bill Gates The Next Outbreak? We\'re Not Ready'),
    title: 'The Next Outbreak? We\'re Not Ready',
    speakerName: 'Bill Gates',
    tedUrl: 'https://www.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready',
    description: 'Bill Gates explains why we should be more scared of a deadly epidemic than nuclear war.',
    durationSeconds: 517,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/2c60223169fd66d3962f9f3c354081824d2914c5_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '6Af6b_wyiwI',
  },
  {
    slug: generateSlug('Dan Buettner How to Live to Be 100+'),
    title: 'How to Live to Be 100+',
    speakerName: 'Dan Buettner',
    tedUrl: 'https://www.ted.com/talks/dan_buettner_how_to_live_to_be_100',
    description: 'Dan Buettner reveals 9 common diet and lifestyle habits that keep them spry past age 100.',
    durationSeconds: 1180,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/139726_800x600.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'ff40YiMmVkU',
  },
  {
    slug: generateSlug('BJ Miller What Really Matters at the End of Life'),
    title: 'What Really Matters at the End of Life',
    speakerName: 'BJ Miller',
    tedUrl: 'https://www.ted.com/talks/bj_miller_what_really_matters_at_the_end_of_life',
    description: 'BJ Miller asks: What really matters at the end of life?',
    durationSeconds: 1148,
    eventName: 'TEDMED',
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/629930bb607d58f65c9b70beab410660a9afd904_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'apbSsILLh28',
  },
  {
    slug: generateSlug('Elizabeth Loftus How Reliable is Your Memory'),
    title: 'How Reliable is Your Memory',
    speakerName: 'Elizabeth Loftus',
    tedUrl: 'https://www.ted.com/talks/elizabeth_loftus_how_reliable_is_your_memory',
    description: 'Elizabeth Loftus studies false memories and explains how easy it is to manipulate memory.',
    durationSeconds: 1057,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/dc329a10500b9d309ad41cfd6f43e417a472b4c5_1600x1200.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'PB2OegI6wvI',
  },
  {
    slug: generateSlug('Caroline Casey Looking Past Limits'),
    title: 'Looking Past Limits',
    speakerName: 'Caroline Casey',
    tedUrl: 'https://www.ted.com/talks/caroline_casey_looking_past_limits',
    description: 'Caroline Casey shares her inspiring journey of looking past the limits others set for her and the limits she set for herself, revealing how embracing vulnerability and pushing boundaries can lead to extraordinary possibilities.',
    durationSeconds: 917,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/2408c227c2e651234d417caf1b48fad0c1a66a1e_800x600.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: null,
  },
  {
    slug: generateSlug('Sam Berns My Philosophy for a Happy Life'),
    title: 'My Philosophy for a Happy Life',
    speakerName: 'Sam Berns',
    tedUrl: 'https://www.ted.com/talks/sam_berns_my_philosophy_for_a_happy_life',
    description: 'Sam Berns shares his philosophy for a happy life.',
    durationSeconds: 765,
    eventName: 'TEDxMidAtlantic',
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/dceb97aa-e320-4f5d-905f-14375f6d2a07/Sam+Berns.jpeg?h=315&w=560',
    language: 'en',
    youtubeVideoId: '36m1o-tM05g',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Success, Failure, and the Drive to Keep Creating'),
    title: 'Success, Failure, and the Drive to Keep Creating',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_success_failure_and_the_drive_to_keep_creating',
    description: 'Elizabeth Gilbert reflects on the complexities of creativity and inspiration.',
    durationSeconds: 439,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/aa39c73bae9d19372ed2059e7c8b0b7eb9099865_1600x1200.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '_waBFUg_oT8',
  },
  {
    slug: generateSlug('Brené Brown The Power of Vulnerability'),
    title: 'The Power of Vulnerability',
    speakerName: 'Brené Brown',
    tedUrl: 'https://www.ted.com/talks/brene_brown_the_power_of_vulnerability',
    description: 'Brené Brown studies human connection -- our ability to empathize, belong, love.',
    durationSeconds: 1250,
    eventName: 'TEDxHouston',
    year: 2011,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/9595cdc1-fd8e-4aa1-863a-2c6641ae3cbb/BreneBrown_2010X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'iCvmsMzlF7o',
  },
  {
    slug: generateSlug('Johann Hari Everything You Think You Know About Addiction is Wrong'),
    title: 'Everything You Think You Know About Addiction is Wrong',
    speakerName: 'Johann Hari',
    tedUrl: 'https://www.ted.com/talks/johann_hari_everything_you_think_you_know_about_addiction_is_wrong',
    description: 'Johann Hari argues that the real cure for addiction is social connection.',
    durationSeconds: 883,
    eventName: 'TEDGlobal',
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/1d2235a94dda9257b3a8feaf486b82aa1ca1e479_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'PY9DcIMGxMs',
  },
  {
    slug: generateSlug('Jill Bolte Taylor My Stroke of Insight'),
    title: 'My Stroke of Insight',
    speakerName: 'Jill Bolte Taylor',
    tedUrl: 'https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight',
    description: 'Jill Bolte Taylor got a research opportunity few brain scientists would wish for: She had a massive stroke, and watched as her brain functions shut down one by one.',
    durationSeconds: 1122,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/eefe30d20338d800bdc70a09dc0f6007e7355a74_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'mYD7Y9CXeUw',
  },
  {
    slug: generateSlug('Jonathan Haidt The Moral Roots of Liberals and Conservatives'),
    title: 'The Moral Roots of Liberals and Conservatives',
    speakerName: 'Jonathan Haidt',
    tedUrl: 'https://www.youtube.com/watch?v=9ei_HSlUxUQ',
    description: 'Jonathan Haidt studies the five moral values that form the basis of our political choices.',
    durationSeconds: 1023,
    eventName: null,
    year: 2014,
    thumbnailUrl: 'https://i.ytimg.com/vi/9ei_HSlUxUQ/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: '9ei_HSlUxUQ',
  },
  {
    slug: generateSlug('Amy Cuddy Your Body Language May Shape Who You Are'),
    title: 'Your Body Language May Shape Who You Are',
    speakerName: 'Amy Cuddy',
    tedUrl: 'https://youtu.be/NDQ1Mi5I4rg',
    description: 'Amy Cuddy shows how "power posing" can boost feelings of confidence.',
    durationSeconds: 1009,
    eventName: 'TEDGlobal',
    year: 2018,
    thumbnailUrl: 'https://i.ytimg.com/vi/NDQ1Mi5I4rg/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'NDQ1Mi5I4rg',
  },
  {
    slug: generateSlug('Helen Fisher The Brain in Love'),
    title: 'The Brain in Love',
    speakerName: 'Helen Fisher',
    tedUrl: 'https://www.ted.com/talks/helen_fisher_the_brain_in_love',
    description: 'Helen Fisher takes on a tricky topic – love – and explains its evolution, its biochemical foundations and its social importance.',
    durationSeconds: 988,
    eventName: null,
    year: 2008,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/dfda28474d713d1de50dd1cc5f67c299c8b6eb80_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'OYfoGTIG7pY',
  },
  {
    slug: generateSlug('Simon Sinek Why Good Leaders Make You Feel Safe'),
    title: 'Why Good Leaders Make You Feel Safe',
    speakerName: 'Simon Sinek',
    tedUrl: 'https://www.ted.com/talks/simon_sinek_why_good_leaders_make_you_feel_safe',
    description: 'Simon Sinek explores how leaders can inspire cooperation, trust and change.',
    durationSeconds: 720,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/b6cccc7593928f4861601289b937d19dac95bed9_1600x1200.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'lmyZMtPVodo',
  },
  {
    slug: generateSlug('Pico Iyer The Art of Stillness'),
    title: 'The Art of Stillness',
    speakerName: 'Pico Iyer',
    tedUrl: 'https://www.ted.com/talks/pico_iyer_the_art_of_stillness',
    description: 'Pico Iyer makes a case for taking time out of our lives to step into the beauty of stillness.',
    durationSeconds: 942,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/bd619eb8f9002797413fb4e886808df331e00608_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'aUBawr1hUwo',
  },
  {
    slug: generateSlug('Tim Ferriss Why You Should Define Your Fears Instead of Your Goals'),
    title: 'Why You Should Define Your Fears Instead of Your Goals',
    speakerName: 'Tim Ferriss',
    tedUrl: 'https://www.ted.com/talks/tim_ferriss_why_you_should_define_your_fears_instead_of_your_goals',
    description: 'Tim Ferriss encourages us to fully envision and write down our fears in detail, in a simple but powerful exercise he calls "fear-setting."',
    durationSeconds: 802,
    eventName: null,
    year: 2017,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/6b784c62-b4d0-4b3a-a1de-89de39b002bc/TimFerriss_2017-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '5J6jAC6XxAI',
  },
  {
    slug: generateSlug('Adam Galinsky How to Speak Up for Yourself'),
    title: 'How to Speak Up for Yourself',
    speakerName: 'Adam Galinsky',
    tedUrl: 'https://www.ted.com/talks/adam_galinsky_how_to_speak_up_for_yourself',
    description: 'Adam Galinsky shares simple tactics to help you speak up for yourself and advance your interests.',
    durationSeconds: 909,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/20d6d96c-e0a3-4a74-ab27-092603dbee9b/AdamGalinsky_2016X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'MEDgtjpycYg',
  },
  {
    slug: generateSlug('Dan Pink The Puzzle of Motivation'),
    title: 'The Puzzle of Motivation',
    speakerName: 'Dan Pink',
    tedUrl: 'https://www.ted.com/talks/dan_pink_the_puzzle_of_motivation',
    description: 'Dan Pink examines the puzzle of motivation, starting with a fact that social scientists know but most managers don\'t: Traditional rewards aren\'t always as effective as we think.',
    durationSeconds: 1117,
    eventName: null,
    year: 2009,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/110884_800x600.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'rrkrvAUbU9Y',
  },
  {
    slug: generateSlug('Jason Fried Why Work Doesn\'t Happen at Work'),
    title: 'Why Work Doesn\'t Happen at Work',
    speakerName: 'Jason Fried',
    tedUrl: 'https://www.ted.com/talks/jason_fried_why_work_doesn_t_happen_at_work',
    description: 'Jason Fried has a radical theory of working: that the office isn\'t a good place to do it.',
    durationSeconds: 1041,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/be91c8b5f3a0798ddca31c761674bfac9e06c970_800x600.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '5XD2kNopsUs',
  },
  {
    slug: generateSlug('Emilie Wapnick Why Some of Us Don\'t Have One True Calling'),
    title: 'Why Some of Us Don\'t Have One True Calling',
    speakerName: 'Emilie Wapnick',
    tedUrl: 'https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling',
    description: 'Emilie Wapnick celebrates being a "multipotentialite" -- someone with many interests and creative pursuits.',
    durationSeconds: 747,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/11e3541d75d4afba6badc2c3c058b8cb4bfe5863_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '4sZdcB6bjI8',
  },
  {
    slug: generateSlug('Jia Jiang What I Learned from 100 Days of Rejection'),
    title: 'What I Learned from 100 Days of Rejection',
    speakerName: 'Jia Jiang',
    tedUrl: 'https://www.ted.com/talks/jia_jiang_what_i_learned_from_100_days_of_rejection',
    description: 'Jia Jiang adventures boldly into a territory so many of us fear: rejection, and shares what he learned.',
    durationSeconds: 932,
    eventName: null,
    year: 2017,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/c4a42ee3-cf78-419d-88a0-cd5194b4432a/JiaJiang_2015X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '-vZXgApsPCQ',
  },
  {
    slug: generateSlug('Sheryl Sandberg Why We Have Too Few Women Leaders'),
    title: 'Why We Have Too Few Women Leaders',
    speakerName: 'Sheryl Sandberg',
    tedUrl: 'https://www.ted.com/talks/sheryl_sandberg_why_we_have_too_few_women_leaders',
    description: 'Sheryl Sandberg looks at why a smaller percentage of women than men reach the top of their professions and offers advice to women aiming for the C-suite.',
    durationSeconds: 929,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/8b324338-3caa-4cda-af41-4a0010b2b65e/SherylSandberg_2010W-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '18uDutylDa4',
  },
  {
    slug: generateSlug('Simon Sinek How Great Leaders Inspire Action'),
    title: 'How Great Leaders Inspire Action',
    speakerName: 'Simon Sinek',
    tedUrl: 'https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action',
    description: 'Simon Sinek presents a simple but powerful model for how leaders inspire action, starting with a golden circle and the question "Why?"',
    durationSeconds: 1115,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/04916ee6e81065c8333e6546184af512eee37bbe_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'qp0HIF3SfI4',
  },
  {
    slug: generateSlug('Beau Lotto Optical Illusions Show How We See'),
    title: 'Optical Illusions Show How We See',
    speakerName: 'Beau Lotto',
    tedUrl: 'https://www.ted.com/talks/beau_lotto_optical_illusions_show_how_we_see',
    description: 'Beau Lotto explains how perception shapes our understanding of the world.',
    durationSeconds: 1140,
    eventName: null,
    year: 2009,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/7a1363b0-1079-4b25-abd9-609420d6c0b9/BeauLotto_2009G-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'mf5otGNbkuc',
  },
  {
    slug: generateSlug('Mel Robbins How to Stop Screwing Yourself Over'),
    title: 'How to Stop Screwing Yourself Over',
    speakerName: 'Mel Robbins',
    tedUrl: 'https://youtu.be/ppfONdsOkWI',
    description: 'Mel Robbins shares the one simple trick that can help you overcome any form of anxiety.',
    durationSeconds: 618,
    eventName: null,
    year: 2019,
    thumbnailUrl: 'https://i.ytimg.com/vi/ppfONdsOkWI/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'ppfONdsOkWI',
  },
  {
    slug: generateSlug('Gretchen Rubin The Four Ways to Successfully Change Behavior'),
    title: 'The Four Ways to Successfully Change Behavior',
    speakerName: 'Gretchen Rubin',
    tedUrl: 'https://www.youtube.com/watch?v=H14bBuluwB8',
    description: 'Gretchen Rubin explores the different ways people respond to expectations and how understanding this can help change habits.',
    durationSeconds: 373,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://i.ytimg.com/vi/H14bBuluwB8/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'H14bBuluwB8',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Your Elusive Creative Genius'),
    title: 'Your Elusive Creative Genius',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_your_elusive_creative_genius',
    description: 'Elizabeth Gilbert muses on the impossible things we expect from artists and geniuses.',
    durationSeconds: 1169,
    eventName: 'TED',
    year: 2009,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/f2f6d094758c36a61b3ee7992a9b197eb4c07979_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '86x-u-tz0MA',
  },
  {
    slug: generateSlug('Kelly McGonigal How to Make Stress Your Friend'),
    title: 'How to Make Stress Your Friend',
    speakerName: 'Kelly McGonigal',
    tedUrl: 'https://www.ted.com/talks/kelly_mcgonigal_how_to_make_stress_your_friend',
    description: 'Kelly McGonigal urges us to see stress as a positive, and introduces us to an unsung mechanism for stress reduction: reaching out to others.',
    durationSeconds: 869,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/4ebfc94d-c426-4019-9060-20edc54dcec8/KellyMcGonigal_2013G-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'RcGyVTAoXEU',
  },
  {
    slug: generateSlug('Hannah Fry The Mathematics of Love'),
    title: 'The Mathematics of Love',
    speakerName: 'Hannah Fry',
    tedUrl: 'https://www.ted.com/talks/hannah_fry_the_mathematics_of_love',
    description: 'Hannah Fry explores the mathematical patterns in human behavior.',
    durationSeconds: 1021,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/eddcaad25cf331e34d366d9ae3edaaaf3989a275_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'yFVXsjVdvmY',
  },
  {
    slug: generateSlug('Derek Sivers How to Start a Movement'),
    title: 'How to Start a Movement',
    speakerName: 'Derek Sivers',
    tedUrl: 'https://www.ted.com/talks/derek_sivers_how_to_start_a_movement',
    description: 'Derek Sivers explains how movements really get started, showing that the first follower is what transforms a lone nut into a leader.',
    durationSeconds: 342,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/6a9cdd2f78fe58b1214125365612fae20bf8b3c5_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'V74AxCqOTvg',
  },
  {
    slug: generateSlug('Esther Perel The Secret to Desire in a Long-Term Relationship'),
    title: 'The Secret to Desire in a Long-Term Relationship',
    speakerName: 'Esther Perel',
    tedUrl: 'https://www.ted.com/talks/esther_perel_the_secret_to_desire_in_a_long_term_relationship',
    description: 'Esther Perel examines what it takes to bring desire back into long-term relationships.',
    durationSeconds: 1151,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/f0420115a72f8b4ce1f54bdf96dd3dc700fee0aa_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'sa0RUmGTCYY',
  },
  {
    slug: generateSlug('Rose Cain Ignite Your Curiosity'),
    title: 'Ignite Your Curiosity',
    speakerName: 'Rose Cain',
    tedUrl: 'https://www.ted.com/talks/rose_cain_ignite_your_curiosity',
    description: 'Rose Cain discusses the importance of curiosity and learning from failure.',
    durationSeconds: 898,
    eventName: null,
    year: 2020,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/61b03fec-d848-409f-bc85-b1c91cfdf179/mqdefault.jpg?h=315&w=560',
    language: 'en',
    youtubeVideoId: 'E9HZyIT6Z-4',
  },
  {
    slug: generateSlug('Daniel Goleman Why Aren\'t We More Compassionate?'),
    title: 'Why Aren\'t We More Compassionate?',
    speakerName: 'Daniel Goleman',
    tedUrl: 'https://www.ted.com/talks/daniel_goleman_why_aren_t_we_more_compassionate',
    description: 'Daniel Goleman asks why we aren\'t more compassionate more of the time and explores the science behind compassion.',
    durationSeconds: 794,
    eventName: null,
    year: 2008,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/a4c517bc935478a8ceb64b5697971d3e0dac08c4_1600x1200.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'r3wyCxHtGd0',
  },
  {
    slug: generateSlug('Celeste Headlee 10 Ways to Have a Better Conversation'),
    title: '10 Ways to Have a Better Conversation',
    speakerName: 'Celeste Headlee',
    tedUrl: 'https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation',
    description: 'Celeste Headlee shares 10 useful rules for having better conversations.',
    durationSeconds: 705,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/42293f27-ad85-4999-a72b-96b6d5d2c398/CelesteHeadlee_2015X_embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'R1vskiVDwl4',
  },
  {
    slug: generateSlug('Ruth Chang How to Make Hard Choices'),
    title: 'How to Make Hard Choices',
    speakerName: 'Ruth Chang',
    tedUrl: 'https://www.ted.com/talks/ruth_chang_how_to_make_hard_choices',
    description: 'Ruth Chang challenges the way we think about making hard choices and offers a new perspective on decision-making.',
    durationSeconds: 882,
    eventName: null,
    year: 2014,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/a74696f0bf766d304840d03388d4234145fed6f1_2400x1800.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '8GQZuzIdeQQ',
  },
  {
    slug: generateSlug('Esther Perel Rethinking Infidelity: A Talk for Anyone Who Has Ever Loved'),
    title: 'Rethinking Infidelity: A Talk for Anyone Who Has Ever Loved',
    speakerName: 'Esther Perel',
    tedUrl: 'https://www.ted.com/talks/esther_perel_rethinking_infidelity_a_talk_for_anyone_who_has_ever_loved',
    description: 'Esther Perel examines infidelity and invites us to explore the psychological dimensions of affairs.',
    durationSeconds: 1291,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/374906e7e2a0f3970763c48ce8e7cc28614444a0_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'P2AUat93a8Q',
  },
  {
    slug: generateSlug('Nora McInerny We Don\'t Move On from Grief. We Move Forward with It'),
    title: 'We Don\'t Move On from Grief. We Move Forward with It',
    speakerName: 'Nora McInerny',
    tedUrl: 'https://www.ted.com/talks/nora_mcinerny_we_don_t_move_on_from_grief_we_move_forward_with_it',
    description: 'Nora McInerny shares her personal experience with grief and loss, showing how we can move forward while still carrying our grief.',
    durationSeconds: 906,
    eventName: null,
    year: 2019,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/637dd322-4f72-4749-b74f-26431096e50c/NoraMcInerny_2018W-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'khkJkR-ipfw',
  },
  {
    slug: generateSlug('Andy Puddicombe All It Takes is 10 Mindful Minutes'),
    title: 'All It Takes is 10 Mindful Minutes',
    speakerName: 'Andy Puddicombe',
    tedUrl: 'https://www.ted.com/talks/andy_puddicombe_all_it_takes_is_10_mindful_minutes',
    description: 'Andy Puddicombe, founder of Headspace, shows how 10 mindful minutes can transform your life.',
    durationSeconds: 565,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/fc646047-513d-40cd-b610-b70f9e582a02/AndyPuddicombe_2012S-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'qzR62JJCMBQ',
  },
  {
    slug: generateSlug('Margaret Heffernan The Dangers of \'Willful Blindness\''),
    title: 'The Dangers of \'Willful Blindness\'',
    speakerName: 'Margaret Heffernan',
    tedUrl: 'https://www.ted.com/talks/margaret_heffernan_the_dangers_of_willful_blindness',
    description: 'Margaret Heffernan examines the phenomenon of willful blindness and why we ignore the obvious at our peril.',
    durationSeconds: 879,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/15f3e40a-7f70-4588-bf3b-931030222f7b/MargaretHeffernan_2013X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'Kn5JRgz3W0o',
  },
  {
    slug: generateSlug('David Steindl-Rast Want to Be Happy? Be Grateful'),
    title: 'Want to Be Happy? Be Grateful',
    speakerName: 'David Steindl-Rast',
    tedUrl: 'https://www.ted.com/talks/david_steindl_rast_want_to_be_happy_be_grateful',
    description: 'Brother David Steindl-Rast, a Benedictine monk and interfaith scholar, argues that happiness stems from gratitude rather than the reverse. He shares a simple practice for grateful living: Stop. Look. Go.',
    durationSeconds: 856,
    eventName: 'TEDGlobal',
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/02722e8404d9e8dd2ec003b249db0ce3d05bda19_1600x1200.jpg',
    language: 'en',
    youtubeVideoId: 'YyBk55G7Keo',
  },
  {
    slug: generateSlug('Ingrid Fetell Lee Where Joy Hides and How to Find It'),
    title: 'Where Joy Hides and How to Find It',
    speakerName: 'Ingrid Fetell Lee',
    tedUrl: 'https://www.ted.com/talks/ingrid_fetell_lee_where_joy_hides_and_how_to_find_it',
    description: 'Ingrid Fetell Lee reveals how we can find more joy in our surroundings through attention to the physical world.',
    durationSeconds: 819,
    eventName: null,
    year: 2018,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/e39fce18-6b1a-4e85-baec-e70d9541b653/IngridFetellLee_2018-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'A_u2WFTfbcg',
  },
  {
    slug: generateSlug('Dan Gilbert The Surprising Science of Happiness'),
    title: 'The Surprising Science of Happiness',
    speakerName: 'Dan Gilbert',
    tedUrl: 'https://www.ted.com/talks/dan_gilbert_the_surprising_science_of_happiness',
    description: 'Dan Gilbert challenges the idea that we\'ll be miserable if we don\'t get what we want, presenting his research on synthetic happiness.',
    durationSeconds: 1280,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/016a827cc0757092a0439ab2a63feca8655b6c29_1600x1200.jpg?h=421&w=560',
    language: 'en',
    youtubeVideoId: '4q1dgn_C0AU',
  },
  {
    slug: generateSlug('Eliza Lay Ryan Sparking Curiosity, Connection, and Creativity'),
    title: 'Sparking Curiosity, Connection, and Creativity',
    speakerName: 'Eliza Lay Ryan',
    tedUrl: 'https://www.ted.com/talks/eliza_lay_ryan_sparking_curiosity_connection_and_creativity',
    description: 'Eliza Lay Ryan explores how curiosity can spark deeper connections and creative thinking.',
    durationSeconds: 967,
    eventName: null,
    year: 2019,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/763bfe42-50b2-482d-81e9-fb90b3a1a654/mqdefault.jpg?h=315&w=560',
    language: 'en',
    youtubeVideoId: 't9WM42gBRlc',
  },
  {
    slug: generateSlug('Steve Jobs How to Live Before You Die'),
    title: 'How to Live Before You Die',
    speakerName: 'Steve Jobs',
    tedUrl: 'https://www.ted.com/talks/steve_jobs_how_to_live_before_you_die',
    description: 'Steve Jobs shares his personal story about connecting the dots, love and loss, and living each day with the knowledge it could be your last.',
    durationSeconds: 906,
    eventName: 'Stanford University commencement',
    year: 2005,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/912a4076-571a-4d8c-b182-69e7383ceb18/SteveJobs_StanfordUniv-embed.jpg?h=315&w=560',
    language: 'en',
    youtubeVideoId: null,
  },
  {
    slug: generateSlug('Gary Lewandowski The Psychology of Betrayal and Recovery'),
    title: 'The Psychology of Betrayal and Recovery',
    speakerName: 'Gary Lewandowski',
    tedUrl: 'https://www.youtube.com/watch?v=Cw2qD87KDHc',
    description: 'Gary Lewandowski explores the psychology behind betrayal and the path to recovery.',
    durationSeconds: 691,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://i.ytimg.com/vi/Cw2qD87KDHc/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'Cw2qD87KDHc',
  },
  {
    slug: generateSlug('Amy Gutmann What It Means to Be a Global Citizen'),
    title: 'What It Means to Be a Global Citizen',
    speakerName: 'Amy Gutmann',
    tedUrl: 'https://youtu.be/ZwGEQcFo9RE',
    description: 'Amy Gutmann explores what it means to be a global citizen in today\'s interconnected world.',
    durationSeconds: 729,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://i.ytimg.com/vi/ZwGEQcFo9RE/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'ZwGEQcFo9RE',
  },
  {
    slug: generateSlug('Robert Waldinger What Makes a Good Life? Lessons from the Longest Study on Happiness'),
    title: 'What Makes a Good Life? Lessons from the Longest Study on Happiness',
    speakerName: 'Robert Waldinger',
    tedUrl: 'https://www.youtube.com/watch?v=HSercnrqeN4',
    description: 'Robert Waldinger shares lessons from a 75-year study on happiness.',
    durationSeconds: 945,
    eventName: 'TEDxBeaconStreet',
    year: 2016,
    thumbnailUrl: 'https://i.ytimg.com/vi/HSercnrqeN4/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'HSercnrqeN4',
  },
  {
    slug: generateSlug('Casey Brown Know Your Worth, and Then Ask for It'),
    title: 'Know Your Worth, and Then Ask for It',
    speakerName: 'Casey Brown',
    tedUrl: 'https://www.youtube.com/watch?v=DjcZrtcBZi4',
    description: 'Casey Brown offers a perspective on how to ask for and get the value you deserve in business.',
    durationSeconds: 1041,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://i.ytimg.com/vi/DjcZrtcBZi4/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'DjcZrtcBZi4',
  },
  {
    slug: generateSlug('Priya Parker 3 Steps to Turn Everyday Get-Togethers Into Transformative Gatherings'),
    title: '3 Steps to Turn Everyday Get-Togethers Into Transformative Gatherings',
    speakerName: 'Priya Parker',
    tedUrl: 'https://www.youtube.com/watch?v=c0KYU2j0TM4',
    description: 'Priya Parker shares her approach to creating meaningful gatherings that bring people together.',
    durationSeconds: 1145,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://i.ytimg.com/vi/c0KYU2j0TM4/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'c0KYU2j0TM4',
  },
  {
    slug: generateSlug('Gever Tulley 5 Dangerous Things You Should Let Your Kids Do'),
    title: '5 Dangerous Things You Should Let Your Kids Do',
    speakerName: 'Gever Tulley',
    tedUrl: 'https://www.youtube.com/watch?v=eIho2S0ZahI',
    description: 'Gever Tulley shares five dangerous things kids should be allowed to do -- and why a little danger is good.',
    durationSeconds: 599,
    eventName: null,
    year: 2014,
    thumbnailUrl: 'https://i.ytimg.com/vi/eIho2S0ZahI/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'eIho2S0ZahI',
  },
  {
    slug: generateSlug('David Blaine How I Held My Breath for 17 Minutes'),
    title: 'How I Held My Breath for 17 Minutes',
    speakerName: 'David Blaine',
    tedUrl: 'https://www.ted.com/talks/david_blaine_how_i_held_my_breath_for_17_minutes',
    description: 'David Blaine describes his journey to hold his breath underwater for 17 minutes.',
    durationSeconds: 1219,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/9ed8ff36f60c73ba894de8370b2ee4182a3aeece_1920x1080.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'XFnGhrC_3Gs',
  },
  {
    slug: generateSlug('Angela Lee Duckworth Grit: The Power of Passion and Perseverance'),
    title: 'Grit: The Power of Passion and Perseverance',
    speakerName: 'Angela Lee Duckworth',
    tedUrl: 'https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance',
    description: 'Angela Lee Duckworth explains her theory of "grit" as a predictor of success.',
    durationSeconds: 373,
    eventName: 'TED Talks Education',
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/49490c34-ef8e-45b1-8037-a4958efc2609/AngelaDuckworth_2013S-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'H14bBuluwB8',
  },
  {
    slug: generateSlug('Brené Brown Listening to Shame'),
    title: 'Listening to Shame',
    speakerName: 'Brené Brown',
    tedUrl: 'https://www.ted.com/talks/brene_brown_listening_to_shame',
    description: 'Brené Brown explores what can happen when people confront their shame head-on.',
    durationSeconds: 1239,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/0d835846-74a5-49d5-b246-7cfc5d3c984e/BreneBrown_2012-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'psN1DORYYV0',
  },
  {
    slug: generateSlug('Shawn Achor The Happy Secret to Better Work'),
    title: 'The Happy Secret to Better Work',
    speakerName: 'Shawn Achor',
    tedUrl: 'https://www.ted.com/talks/shawn_achor_the_happy_secret_to_better_work',
    description: 'Shawn Achor argues that happiness inspires productivity.',
    durationSeconds: 741,
    eventName: 'TEDxBloomington',
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/e02ed13dcc2684221ce59429a722479dd13661fb_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'fLJsdqxnZb0',
  },
  {
    slug: generateSlug('Carla Harris How to Find the Person Who Can Help You Get Ahead at Work'),
    title: 'How to Find the Person Who Can Help You Get Ahead at Work',
    speakerName: 'Carla Harris',
    tedUrl: 'https://www.ted.com/talks/carla_harris_how_to_find_the_person_who_can_help_you_get_ahead_at_work',
    description: 'Carla Harris explains the difference between a sponsor and a mentor.',
    durationSeconds: 804,
    eventName: null,
    year: 2019,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/90354933-011a-4692-ab14-5326c7b40bfe/CarlaHarris_2018W-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'gpE_W50OTUc',
  },
  {
    slug: generateSlug('Pamela Meyer How to Spot a Liar'),
    title: 'How to Spot a Liar',
    speakerName: 'Pamela Meyer',
    tedUrl: 'https://www.ted.com/talks/pamela_meyer_how_to_spot_a_liar',
    description: 'Pamela Meyer shows the manners and "hotspots" used by those trained to recognize deception.',
    durationSeconds: 1131,
    eventName: null,
    year: 2011,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/40c841c7-43c2-4386-a885-9600f528ea55/PamelaMeyer_2011G-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'P_6vDLq64gE',
  },
  {
    slug: generateSlug('Steven Johnson Where Good Ideas Come From'),
    title: 'Where Good Ideas Come From',
    speakerName: 'Steven Johnson',
    tedUrl: 'https://www.ted.com/talks/steven_johnson_where_good_ideas_come_from',
    description: 'Steven Johnson explores the history of innovation and shares his theory about where good ideas come from.',
    durationSeconds: 1097,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/c8244a05-ac8e-45c6-9b06-ac22113031db/StevenJohnson-2010G-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '0af00UcTO-c',
  },
  {
    slug: generateSlug('Tim Urban Inside the Mind of a Master Procrastinator'),
    title: 'Inside the Mind of a Master Procrastinator',
    speakerName: 'Tim Urban',
    tedUrl: 'https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator',
    description: 'Tim Urban takes us on a journey through YouTube binges, Wikipedia rabbit holes and bouts of staring out the window.',
    durationSeconds: 844,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/d5d00454-d7aa-434c-8fae-ff2bc97c5f02/TimUrban_2016-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'arj7oStGLkU',
  },
  {
    slug: generateSlug('Sam Harris Can We Build AI Without Losing Control Over It?'),
    title: 'Can We Build AI Without Losing Control Over It?',
    speakerName: 'Sam Harris',
    tedUrl: 'https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it',
    description: 'Sam Harris confronts us with a question that may matter more than any in human history: Can we build AI without losing control over it?',
    durationSeconds: 868,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/51c9b741-275c-4ea0-bb9d-11b9aa8d1165/SamHarris_2016T-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '8nt3edWLgIg',
  },
  {
    slug: generateSlug('Charlie Mackesy Abandon The Idea Of Being Good And Just Try'),
    title: 'Abandon The Idea Of Being Good And Just Try',
    speakerName: 'Charlie Mackesy',
    tedUrl: 'https://www.youtube.com/watch?v=cRC0Kvrn93Q',
    description: 'Charlie Mackesy shares his thoughts on abandoning the idea of being good and just trying.',
    durationSeconds: 1003,
    eventName: 'TEDxFrensham',
    year: 2018,
    thumbnailUrl: 'https://i.ytimg.com/vi/cRC0Kvrn93Q/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'cRC0Kvrn93Q',
  },
  {
    slug: generateSlug('Al Vernacchio Sex Needs a New Metaphor. Here\'s One'),
    title: 'Sex Needs a New Metaphor. Here\'s One',
    speakerName: 'Al Vernacchio',
    tedUrl: 'https://www.ted.com/talks/al_vernacchio_sex_needs_a_new_metaphor_here_s_one',
    description: 'Al Vernacchio argues that our current metaphor for sex is broken and proposes a healthier alternative.',
    durationSeconds: 502,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/c4e17623-f27b-4165-a85f-854b54f4958e/AlVernacchio_2012-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'xF-CX9mAHPo',
  },
  {
    slug: generateSlug('David Allen The Art of Stress-Free Productivity'),
    title: 'The Art of Stress-Free Productivity',
    speakerName: 'David Allen',
    tedUrl: 'https://www.ted.com/talks/david_allen_the_art_of_stress_free_productivity',
    description: 'David Allen, creator of Getting Things Done, shares his approach to stress-free productivity.',
    durationSeconds: 1336,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://i.ytimg.com/vi/CHxhjDPKfbY/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'CHxhjDPKfbY',
  },
  {
    slug: generateSlug('Megan Phelps-Roper I Grew Up in the Westboro Baptist Church. Here\'s Why I Left'),
    title: 'I Grew Up in the Westboro Baptist Church. Here\'s Why I Left',
    speakerName: 'Megan Phelps-Roper',
    tedUrl: 'https://www.ted.com/talks/megan_phelps_roper_i_grew_up_in_the_westboro_baptist_church_here_s_why_i_left',
    description: 'Megan Phelps-Roper shares details of life inside America\'s most controversial church and describes how conversations on Twitter helped her see another side.',
    durationSeconds: 918,
    eventName: null,
    year: 2017,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/a797a8a0-a6ea-44c7-876c-0423df616f86/MeganPhelpsRoper_2017S-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'bVV2Zk88beY',
  },
  {
    slug: generateSlug('Michael Norton How to Buy Happiness'),
    title: 'How to Buy Happiness',
    speakerName: 'Michael Norton',
    tedUrl: 'https://www.ted.com/talks/michael_norton_how_to_buy_happiness',
    description: 'Michael Norton shares surprising research on how spending money on others can make you happier.',
    durationSeconds: 659,
    eventName: null,
    year: 2012,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/dac773c5-9c88-4502-a01b-454fb89c5d56/MichaelNorton_2011X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'PsihkFWDt3Y',
  },
  {
    slug: generateSlug('Tom Wujec Build a Tower, Build a Team'),
    title: 'Build a Tower, Build a Team',
    speakerName: 'Tom Wujec',
    tedUrl: 'https://www.ted.com/talks/tom_wujec_build_a_tower_build_a_team',
    description: 'Tom Wujec presents surprising research about what makes teams work effectively through the Marshmallow Challenge.',
    durationSeconds: 443,
    eventName: null,
    year: 2010,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/2d39c28c-132c-48a4-bce5-eb29c6be862a/TomWujec_2010U-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'H0_yKBitO8M',
  },
  {
    slug: generateSlug('Mandy Len Catron A Better Way to Talk About Love'),
    title: 'A Better Way to Talk About Love',
    speakerName: 'Mandy Len Catron',
    tedUrl: 'https://www.ted.com/talks/mandy_len_catron_a_better_way_to_talk_about_love',
    description: 'Mandy Len Catron explores the language and metaphors we use to talk about love.',
    durationSeconds: 918,
    eventName: null,
    year: 2017,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/13ca89ec-6bca-4488-b6be-0f5ccae19b45/MandyLenCatron_SFU_2015X-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'zMWYQRKuc5M',
  },
  {
    slug: generateSlug('Adam Grant The Surprising Habits of Original Thinkers'),
    title: 'The Surprising Habits of Original Thinkers',
    speakerName: 'Adam Grant',
    tedUrl: 'https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers',
    description: 'Adam Grant explores the habits of original thinkers and shows that procrastination can be a virtue for creativity.',
    durationSeconds: 925,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/93b0a599-6bd5-44fb-b61f-61556ed9d413/AdamGrant_2016-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'fxbCHn6gE3U',
  },
  {
    slug: generateSlug('Chip Conley What Baby Boomers Can Learn from Millennials at Work -- and Vice Versa'),
    title: 'What Baby Boomers Can Learn from Millennials at Work -- and Vice Versa',
    speakerName: 'Chip Conley',
    tedUrl: 'https://www.ted.com/talks/chip_conley_what_baby_boomers_can_learn_from_millennials_at_work_and_vice_versa',
    description: 'Chip Conley explores the mutual mentorship between different generations in the workplace.',
    durationSeconds: 743,
    eventName: null,
    year: 2018,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/928a3362-6bef-4127-b36e-e0387843529f/ChipConley_2018S-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '7p1nCRQCiUM',
  },
  {
    slug: generateSlug('Laura Vanderkam How to Gain Control of Your Free Time'),
    title: 'How to Gain Control of Your Free Time',
    speakerName: 'Laura Vanderkam',
    tedUrl: 'https://youtu.be/gmj-azFbpkA',
    description: 'Laura Vanderkam shares practical strategies for making time for the things that matter most.',
    durationSeconds: 1125,
    eventName: null,
    year: 2016,
    thumbnailUrl: 'https://i.ytimg.com/vi/gmj-azFbpkA/hqdefault.jpg',
    language: 'en',
    youtubeVideoId: 'gmj-azFbpkA',
  },
  {
    slug: generateSlug('Ray Dalio How to Build a Company Where the Best Ideas Win'),
    title: 'How to Build a Company Where the Best Ideas Win',
    speakerName: 'Ray Dalio',
    tedUrl: 'https://www.ted.com/talks/ray_dalio_how_to_build_a_company_where_the_best_ideas_win',
    description: 'Ray Dalio shares the unconventional principles he developed to create a culture of radical truth and transparency.',
    durationSeconds: 994,
    eventName: null,
    year: 2017,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/59742aeb-aee5-41bc-ba7e-d30e7f94a172/RayDalio_2017-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'HXbsVbFAczg',
  },
  {
    slug: generateSlug('Shonda Rhimes My Year of Saying Yes to Everything'),
    title: 'My Year of Saying Yes to Everything',
    speakerName: 'Shonda Rhimes',
    tedUrl: 'https://www.ted.com/talks/shonda_rhimes_my_year_of_saying_yes_to_everything',
    description: 'Shonda Rhimes, the titan behind Grey\'s Anatomy, Scandal and How to Get Away With Murder, shares how saying yes to the things that scare her transformed her life and work.',
    durationSeconds: 1125,
    eventName: 'TED2016',
    year: 2016,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/e15c8db4-8e16-4255-82b6-22e90ec5d6eb/ShondaRhimes_2016-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'gmj-azFbpkA',
  },
  {
    slug: generateSlug('Peter Singer The Why and How of Effective Altruism'),
    title: 'The Why and How of Effective Altruism',
    speakerName: 'Peter Singer',
    tedUrl: 'https://www.ted.com/talks/peter_singer_the_why_and_how_of_effective_altruism',
    description: 'Peter Singer explores how we can find more meaning in our lives by helping others most effectively.',
    durationSeconds: 1040,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/talkstar-photos.s3.amazonaws.com/uploads/b00280c9-dc2e-4abb-b15b-3eef4e357798/PeterSinger_2013-embed.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'Diuv3XZQXyc',
  },
  {
    slug: generateSlug('Paul Piff Does Money Make You Mean?'),
    title: 'Does Money Make You Mean?',
    speakerName: 'Paul Piff',
    tedUrl: 'https://www.ted.com/talks/paul_piff_does_money_make_you_mean',
    description: 'Paul Piff shares research that shows how wealth can make people less compassionate and more entitled.',
    durationSeconds: 996,
    eventName: null,
    year: 2013,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/6306acdec9c120286bec64b6514715f16ee5516d_1600x1200.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'bJ8Kq1wucsk',
  },
  {
    slug: generateSlug('Bill Gross The Single Biggest Reason Why Startups Succeed'),
    title: 'The Single Biggest Reason Why Startups Succeed',
    speakerName: 'Bill Gross',
    tedUrl: 'https://www.ted.com/talks/bill_gross_the_single_biggest_reason_why_startups_succeed',
    description: 'Bill Gross reveals the single biggest reason why startups succeed after analyzing hundreds of companies.',
    durationSeconds: 401,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/55c617f514a04f27d3ac75bde232665257c64326_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: 'bNpx7gpSqbY',
  },
  {
    slug: generateSlug('Carol Dweck The Power of Believing That You Can Improve'),
    title: 'The Power of Believing That You Can Improve',
    speakerName: 'Carol Dweck',
    tedUrl: 'https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve',
    description: 'Carol Dweck describes two ways to think about a problem that\'s slightly too hard for you to solve: growth mindset versus fixed mindset.',
    durationSeconds: 625,
    eventName: null,
    year: 2014,
    thumbnailUrl: 'https://pi.tedcdn.com/r/pe.tedcdn.com/images/ted/85582d553035da22504c315ba5ec7ed727f16354_2880x1620.jpg?h=316&w=560',
    language: 'en',
    youtubeVideoId: '_X0mgOOSpLU',
  }
];
