import { generateSlug } from './helpers';

// Unique TED talks extracted from CSV files
// Note: Some talks appear multiple times across different cards
export const talksSeedData = [
  {
    slug: generateSlug('Stuart Brown Play is More Than Just Fun'),
    title: 'Play is More Than Just Fun',
    speakerName: 'Stuart Brown',
    tedUrl: 'https://www.youtube.com/watch?v=cRC0Kvrn93Q',
    description: 'Stuart Brown says play is more than just joyful and energy-burning. It\'s deeply connected with innovation, adaptation, and resilience.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/cRC0Kvrn93Q/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('David Blaine How I Held My Breath for 17 Minutes'),
    title: 'How I Held My Breath for 17 Minutes',
    speakerName: 'David Blaine',
    tedUrl: 'https://www.ted.com/talks/david_blaine_how_i_held_my_breath_for_17_minutes',
    description: 'David Blaine describes his journey to hold his breath underwater for 17 minutes.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/david_blaine_how_i_held_my_breath_for_17_minutes.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Jill Bolte Taylor My Stroke of Insight'),
    title: 'My Stroke of Insight',
    speakerName: 'Jill Bolte Taylor',
    tedUrl: 'https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight',
    description: 'Jill Bolte Taylor got a research opportunity few brain scientists would wish for: She had a massive stroke, and watched as her brain functions shut down one by one.',
    durationSeconds: null,
    eventName: null,
    year: 2008,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Brené Brown The Power of Vulnerability'),
    title: 'The Power of Vulnerability',
    speakerName: 'Brené Brown',
    tedUrl: 'https://www.ted.com/talks/brene_brown_the_power_of_vulnerability',
    description: 'Brené Brown studies human connection -- our ability to empathize, belong, love.',
    durationSeconds: 1223,
    eventName: 'TEDxHouston',
    year: 2010,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/brene_brown_the_power_of_vulnerability.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Jonathan Haidt The Moral Roots of Liberals and Conservatives'),
    title: 'The Moral Roots of Liberals and Conservatives',
    speakerName: 'Jonathan Haidt',
    tedUrl: 'https://www.youtube.com/watch?v=9ei_HSlUxUQ',
    description: 'Jonathan Haidt studies the five moral values that form the basis of our political choices.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/9ei_HSlUxUQ/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Angela Lee Duckworth Grit: The Power of Passion and Perseverance'),
    title: 'Grit: The Power of Passion and Perseverance',
    speakerName: 'Angela Lee Duckworth',
    tedUrl: 'https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance',
    description: 'Angela Lee Duckworth explains her theory of "grit" as a predictor of success.',
    durationSeconds: 366,
    eventName: 'TED Talks Education',
    year: 2013,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Helen Fisher The Brain in Love'),
    title: 'The Brain in Love',
    speakerName: 'Helen Fisher',
    tedUrl: 'https://www.ted.com/talks/helen_fisher_the_brain_in_love',
    description: 'Helen Fisher takes on a tricky topic – love – and explains its evolution, its biochemical foundations and its social importance.',
    durationSeconds: null,
    eventName: null,
    year: 2008,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/helen_fisher_the_brain_in_love.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Simon Sinek Why Good Leaders Make You Feel Safe'),
    title: 'Why Good Leaders Make You Feel Safe',
    speakerName: 'Simon Sinek',
    tedUrl: 'https://www.ted.com/talks/simon_sinek_why_good_leaders_make_you_feel_safe',
    description: 'Simon Sinek explores how leaders can inspire cooperation, trust and change.',
    durationSeconds: 720,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/simon_sinek_why_good_leaders_make_you_feel_safe.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Pico Iyer The Art of Stillness'),
    title: 'The Art of Stillness',
    speakerName: 'Pico Iyer',
    tedUrl: 'https://www.ted.com/talks/pico_iyer_the_art_of_stillness',
    description: 'Pico Iyer makes a case for taking time out of our lives to step into the beauty of stillness.',
    durationSeconds: 917,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/pico_iyer_the_art_of_stillness.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Bryan Stevenson We Need to Talk About an Injustice'),
    title: 'We Need to Talk About an Injustice',
    speakerName: 'Bryan Stevenson',
    tedUrl: 'https://www.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice',
    description: 'Bryan Stevenson presents the statistics and stories of our racially biased justice system.',
    durationSeconds: 1422,
    eventName: 'TED',
    year: 2012,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Amy Cuddy Your Body Language May Shape Who You Are'),
    title: 'Your Body Language May Shape Who You Are',
    speakerName: 'Amy Cuddy',
    tedUrl: 'https://youtu.be/NDQ1Mi5I4rg',
    description: 'Amy Cuddy shows how "power posing" can boost feelings of confidence.',
    durationSeconds: 1265,
    eventName: 'TEDGlobal',
    year: 2012,
    thumbnailUrl: 'https://img.youtube.com/vi/NDQ1Mi5I4rg/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Bill Gates The Next Outbreak? We\'re Not Ready'),
    title: 'The Next Outbreak? We\'re Not Ready',
    speakerName: 'Bill Gates',
    tedUrl: 'https://www.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready',
    description: 'Bill Gates explains why we should be more scared of a deadly epidemic than nuclear war.',
    durationSeconds: null,
    eventName: null,
    year: 2015,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Johann Hari Everything You Think You Know About Addiction is Wrong'),
    title: 'Everything You Think You Know About Addiction is Wrong',
    speakerName: 'Johann Hari',
    tedUrl: 'https://www.ted.com/talks/johann_hari_everything_you_think_you_know_about_addiction_is_wrong',
    description: 'Johann Hari argues that the real cure for addiction is social connection.',
    durationSeconds: 885,
    eventName: 'TEDGlobal',
    year: 2015,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/johann_hari_everything_you_think_you_know_about_addiction_is_wrong.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Dan Buettner How to Live to Be 100+'),
    title: 'How to Live to Be 100+',
    speakerName: 'Dan Buettner',
    tedUrl: 'https://www.ted.com/talks/dan_buettner_how_to_live_to_be_100',
    description: 'Dan Buettner reveals 9 common diet and lifestyle habits that keep them spry past age 100.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/dan_buettner_how_to_live_to_be_100.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('BJ Miller What Really Matters at the End of Life'),
    title: 'What Really Matters at the End of Life',
    speakerName: 'BJ Miller',
    tedUrl: 'https://www.ted.com/talks/bj_miller_what_really_matters_at_the_end_of_life',
    description: 'BJ Miller asks: What really matters at the end of life?',
    durationSeconds: 1146,
    eventName: 'TEDMED',
    year: 2015,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/bj_miller_what_really_matters_at_the_end_of_life.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Loftus How Reliable is Your Memory'),
    title: 'How Reliable is Your Memory',
    speakerName: 'Elizabeth Loftus',
    tedUrl: 'https://www.ted.com/talks/elizabeth_loftus_how_reliable_is_your_memory',
    description: 'Elizabeth Loftus studies false memories and explains how easy it is to manipulate memory.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/elizabeth_loftus_how_reliable_is_your_memory.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Caroline Casey Looking Past Limits'),
    title: 'Looking Past Limits',
    speakerName: 'Caroline Casey',
    tedUrl: 'https://www.ted.com/talks/caroline_casey_looking_past_limits',
    description: 'Caroline Casey tells about her journey beyond limits.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/caroline_casey_looking_past_limits.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Sam Berns My Philosophy for a Happy Life'),
    title: 'My Philosophy for a Happy Life',
    speakerName: 'Sam Berns',
    tedUrl: 'https://www.ted.com/talks/sam_berns_my_philosophy_for_a_happy_life',
    description: 'Sam Berns shares his philosophy for a happy life.',
    durationSeconds: 758,
    eventName: 'TEDxMidAtlantic',
    year: 2013,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/sam_berns_my_philosophy_for_a_happy_life.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Success, Failure, and the Drive to Keep Creating'),
    title: 'Success, Failure, and the Drive to Keep Creating',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_success_failure_and_the_drive_to_keep_creating',
    description: 'Elizabeth Gilbert reflects on the complexities of creativity and inspiration.',
    durationSeconds: 1096,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/elizabeth_gilbert_success_failure_and_the_drive_to_keep_creating.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Shawn Achor The Happy Secret to Better Work'),
    title: 'The Happy Secret to Better Work',
    speakerName: 'Shawn Achor',
    tedUrl: 'https://www.ted.com/talks/shawn_achor_the_happy_secret_to_better_work',
    description: 'Shawn Achor argues that happiness inspires productivity.',
    durationSeconds: 744,
    eventName: 'TEDxBloomington',
    year: 2011,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/shawn_achor_the_happy_secret_to_better_work.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Beau Lotto Optical Illusions Show How We See'),
    title: 'Optical Illusions Show How We See',
    speakerName: 'Beau Lotto',
    tedUrl: 'https://www.ted.com/talks/beau_lotto_optical_illusions_show_how_we_see',
    description: 'Beau Lotto explains how perception shapes our understanding of the world.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/beau_lotto_optical_illusions_show_how_we_see.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Your Elusive Creative Genius'),
    title: 'Your Elusive Creative Genius',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_your_elusive_creative_genius',
    description: 'Elizabeth Gilbert muses on the impossible things we expect from artists and geniuses.',
    durationSeconds: 1145,
    eventName: 'TED',
    year: 2009,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/elizabeth_gilbert_your_elusive_creative_genius.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Hannah Fry The Mathematics of Love'),
    title: 'The Mathematics of Love',
    speakerName: 'Hannah Fry',
    tedUrl: 'https://www.ted.com/talks/hannah_fry_the_mathematics_of_love',
    description: 'Hannah Fry explores the mathematical patterns in human behavior.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/hannah_fry_the_mathematics_of_love.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Carla Harris How to Find the Person Who Can Help You Get Ahead at Work'),
    title: 'How to Find the Person Who Can Help You Get Ahead at Work',
    speakerName: 'Carla Harris',
    tedUrl: 'https://www.ted.com/talks/carla_harris_how_to_find_the_person_who_can_help_you_get_ahead_at_work',
    description: 'Carla Harris explains the difference between a sponsor and a mentor.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/carla_harris_how_to_find_the_person_who_can_help_you_get_ahead_at_work.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Robert Waldinger What Makes a Good Life? Lessons from the Longest Study on Happiness'),
    title: 'What Makes a Good Life? Lessons from the Longest Study on Happiness',
    speakerName: 'Robert Waldinger',
    tedUrl: 'https://www.youtube.com/watch?v=HSercnrqeN4',
    description: 'Robert Waldinger shares lessons from a 75-year study on happiness.',
    durationSeconds: 770,
    eventName: 'TEDxBeaconStreet',
    year: 2015,
    thumbnailUrl: 'https://img.youtube.com/vi/HSercnrqeN4/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Derek Sivers How to Start a Movement'),
    title: 'How to Start a Movement',
    speakerName: 'Derek Sivers',
    tedUrl: 'https://www.ted.com/talks/derek_sivers_how_to_start_a_movement',
    description: 'Derek Sivers explains how movements really get started, showing that the first follower is what transforms a lone nut into a leader.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/derek_sivers_how_to_start_a_movement.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Tim Ferriss Why You Should Define Your Fears Instead of Your Goals'),
    title: 'Why You Should Define Your Fears Instead of Your Goals',
    speakerName: 'Tim Ferriss',
    tedUrl: 'https://www.ted.com/talks/tim_ferriss_why_you_should_define_your_fears_instead_of_your_goals',
    description: 'Tim Ferriss encourages us to fully envision and write down our fears in detail, in a simple but powerful exercise he calls "fear-setting."',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/tim_ferriss_why_you_should_define_your_fears_instead_of_your_goals.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Adam Galinsky How to Speak Up for Yourself'),
    title: 'How to Speak Up for Yourself',
    speakerName: 'Adam Galinsky',
    tedUrl: 'https://www.ted.com/talks/adam_galinsky_how_to_speak_up_for_yourself',
    description: 'Adam Galinsky shares simple tactics to help you speak up for yourself and advance your interests.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/adam_galinsky_how_to_speak_up_for_yourself.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Dan Pink The Puzzle of Motivation'),
    title: 'The Puzzle of Motivation',
    speakerName: 'Dan Pink',
    tedUrl: 'https://www.ted.com/talks/dan_pink_the_puzzle_of_motivation',
    description: 'Dan Pink examines the puzzle of motivation, starting with a fact that social scientists know but most managers don\'t: Traditional rewards aren\'t always as effective as we think.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/dan_pink_the_puzzle_of_motivation.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Mel Robbins How to Stop Screwing Yourself Over'),
    title: 'How to Stop Screwing Yourself Over',
    speakerName: 'Mel Robbins',
    tedUrl: 'https://youtu.be/ppfONdsOkWI',
    description: 'Mel Robbins shares the one simple trick that can help you overcome any form of anxiety.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/ppfONdsOkWI/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Gretchen Rubin The Four Ways to Successfully Change Behavior'),
    title: 'The Four Ways to Successfully Change Behavior',
    speakerName: 'Gretchen Rubin',
    tedUrl: 'https://www.youtube.com/watch?v=H14bBuluwB8',
    description: 'Gretchen Rubin explores the different ways people respond to expectations and how understanding this can help change habits.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/H14bBuluwB8/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Jason Fried Why Work Doesn\'t Happen at Work'),
    title: 'Why Work Doesn\'t Happen at Work',
    speakerName: 'Jason Fried',
    tedUrl: 'https://www.ted.com/talks/jason_fried_why_work_doesn_t_happen_at_work',
    description: 'Jason Fried has a radical theory of working: that the office isn\'t a good place to do it.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/jason_fried_why_work_doesn_t_happen_at_work.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Emilie Wapnick Why Some of Us Don\'t Have One True Calling'),
    title: 'Why Some of Us Don\'t Have One True Calling',
    speakerName: 'Emilie Wapnick',
    tedUrl: 'https://www.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling',
    description: 'Emilie Wapnick celebrates being a "multipotentialite" -- someone with many interests and creative pursuits.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/emilie_wapnick_why_some_of_us_don_t_have_one_true_calling.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Jia Jiang What I Learned from 100 Days of Rejection'),
    title: 'What I Learned from 100 Days of Rejection',
    speakerName: 'Jia Jiang',
    tedUrl: 'https://www.ted.com/talks/jia_jiang_what_i_learned_from_100_days_of_rejection',
    description: 'Jia Jiang adventures boldly into a territory so many of us fear: rejection, and shares what he learned.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/jia_jiang_what_i_learned_from_100_days_of_rejection.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Kelly McGonigal How to Make Stress Your Friend'),
    title: 'How to Make Stress Your Friend',
    speakerName: 'Kelly McGonigal',
    tedUrl: 'https://www.ted.com/talks/kelly_mcgonigal_how_to_make_stress_your_friend',
    description: 'Kelly McGonigal urges us to see stress as a positive, and introduces us to an unsung mechanism for stress reduction: reaching out to others.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/kelly_mcgonigal_how_to_make_stress_your_friend.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Casey Brown Know Your Worth, and Then Ask for It'),
    title: 'Know Your Worth, and Then Ask for It',
    speakerName: 'Casey Brown',
    tedUrl: 'https://www.youtube.com/watch?v=DjcZrtcBZi4',
    description: 'Casey Brown offers a perspective on how to ask for and get the value you deserve in business.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/DjcZrtcBZi4/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Sheryl Sandberg Why We Have Too Few Women Leaders'),
    title: 'Why We Have Too Few Women Leaders',
    speakerName: 'Sheryl Sandberg',
    tedUrl: 'https://www.ted.com/talks/sheryl_sandberg_why_we_have_too_few_women_leaders',
    description: 'Sheryl Sandberg looks at why a smaller percentage of women than men reach the top of their professions and offers advice to women aiming for the C-suite.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/sheryl_sandberg_why_we_have_too_few_women_leaders.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Simon Sinek How Great Leaders Inspire Action'),
    title: 'How Great Leaders Inspire Action',
    speakerName: 'Simon Sinek',
    tedUrl: 'https://www.ted.com/talks/simon_sinek_how_great_leaders_inspire_action',
    description: 'Simon Sinek presents a simple but powerful model for how leaders inspire action, starting with a golden circle and the question "Why?"',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/simon_sinek_how_great_leaders_inspire_action.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Megan Phelps-Roper I Grew Up in the Westboro Baptist Church. Here\'s Why I Left'),
    title: 'I Grew Up in the Westboro Baptist Church. Here\'s Why I Left',
    speakerName: 'Megan Phelps-Roper',
    tedUrl: 'https://www.ted.com/talks/megan_phelps_roper_i_grew_up_in_the_westboro_baptist_church_here_s_why_i_left',
    description: 'Megan Phelps-Roper shares details of life inside America\'s most controversial church and describes how conversations on Twitter helped her see another side.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/megan_phelps_roper_i_grew_up_in_the_westboro_baptist_church_here_s_why_i_left.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Steve Jobs How to Live Before You Die'),
    title: 'How to Live Before You Die',
    speakerName: 'Steve Jobs',
    tedUrl: 'https://www.ted.com/talks/steve_jobs_how_to_live_before_you_die',
    description: 'Steve Jobs shares his personal story about connecting the dots, love and loss, and living each day with the knowledge it could be your last.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/steve_jobs_how_to_live_before_you_die.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('David Steindl-Rast Want to Be Happy? Be Grateful'),
    title: 'Want to Be Happy? Be Grateful',
    speakerName: 'David Steindl-Rast',
    tedUrl: 'https://youtu.be/YyBk55G7Keo',
    description: 'David Steindl-Rast explains the key to living gratefully and how it can transform your life.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/YyBk55G7Keo/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Ingrid Fetell Lee Where Joy Hides and How to Find It'),
    title: 'Where Joy Hides and How to Find It',
    speakerName: 'Ingrid Fetell Lee',
    tedUrl: 'https://www.ted.com/talks/ingrid_fetell_lee_where_joy_hides_and_how_to_find_it',
    description: 'Ingrid Fetell Lee reveals how we can find more joy in our surroundings through attention to the physical world.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/ingrid_fetell_lee_where_joy_hides_and_how_to_find_it.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Dan Gilbert The Surprising Science of Happiness'),
    title: 'The Surprising Science of Happiness',
    speakerName: 'Dan Gilbert',
    tedUrl: 'https://www.ted.com/talks/dan_gilbert_the_surprising_science_of_happiness',
    description: 'Dan Gilbert challenges the idea that we\'ll be miserable if we don\'t get what we want, presenting his research on synthetic happiness.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/dan_gilbert_the_surprising_science_of_happiness.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Priya Parker 3 Steps to Turn Everyday Get-Togethers Into Transformative Gatherings'),
    title: '3 Steps to Turn Everyday Get-Togethers Into Transformative Gatherings',
    speakerName: 'Priya Parker',
    tedUrl: 'https://www.youtube.com/watch?v=c0KYU2j0TM4',
    description: 'Priya Parker shares her approach to creating meaningful gatherings that bring people together.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/c0KYU2j0TM4/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Esther Perel The Secret to Desire in a Long-Term Relationship'),
    title: 'The Secret to Desire in a Long-Term Relationship',
    speakerName: 'Esther Perel',
    tedUrl: 'https://www.ted.com/talks/esther_perel_the_secret_to_desire_in_a_long_term_relationship',
    description: 'Esther Perel examines what it takes to bring desire back into long-term relationships.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/esther_perel_the_secret_to_desire_in_a_long_term_relationship.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Eliza Lay Ryan Sparking Curiosity, Connection, and Creativity'),
    title: 'Sparking Curiosity, Connection, and Creativity',
    speakerName: 'Eliza Lay Ryan',
    tedUrl: 'https://www.ted.com/talks/eliza_lay_ryan_sparking_curiosity_connection_and_creativity',
    description: 'Eliza Lay Ryan explores how curiosity can spark deeper connections and creative thinking.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/eliza_lay_ryan_sparking_curiosity_connection_and_creativity.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Rose Cain Ignite Your Curiosity'),
    title: 'Ignite Your Curiosity',
    speakerName: 'Rose Cain',
    tedUrl: 'https://www.ted.com/talks/rose_cain_ignite_your_curiosity',
    description: 'Rose Cain discusses the importance of curiosity and learning from failure.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/rose_cain_ignite_your_curiosity.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Daniel Goleman Why Aren\'t We More Compassionate?'),
    title: 'Why Aren\'t We More Compassionate?',
    speakerName: 'Daniel Goleman',
    tedUrl: 'https://www.ted.com/talks/daniel_goleman_why_aren_t_we_more_compassionate',
    description: 'Daniel Goleman asks why we aren\'t more compassionate more of the time and explores the science behind compassion.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/daniel_goleman_why_aren_t_we_more_compassionate.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Celeste Headlee 10 Ways to Have a Better Conversation'),
    title: '10 Ways to Have a Better Conversation',
    speakerName: 'Celeste Headlee',
    tedUrl: 'https://www.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation',
    description: 'Celeste Headlee shares 10 useful rules for having better conversations.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/celeste_headlee_10_ways_to_have_a_better_conversation.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Ruth Chang How to Make Hard Choices'),
    title: 'How to Make Hard Choices',
    speakerName: 'Ruth Chang',
    tedUrl: 'https://www.ted.com/talks/ruth_chang_how_to_make_hard_choices',
    description: 'Ruth Chang challenges the way we think about making hard choices and offers a new perspective on decision-making.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/ruth_chang_how_to_make_hard_choices.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Esther Perel Rethinking Infidelity: A Talk for Anyone Who Has Ever Loved'),
    title: 'Rethinking Infidelity: A Talk for Anyone Who Has Ever Loved',
    speakerName: 'Esther Perel',
    tedUrl: 'https://www.ted.com/talks/esther_perel_rethinking_infidelity_a_talk_for_anyone_who_has_ever_loved',
    description: 'Esther Perel examines infidelity and invites us to explore the psychological dimensions of affairs.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/esther_perel_rethinking_infidelity_a_talk_for_anyone_who_has_ever_loved.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Gary Lewandowski The Psychology of Betrayal and Recovery'),
    title: 'The Psychology of Betrayal and Recovery',
    speakerName: 'Gary Lewandowski',
    tedUrl: 'https://www.youtube.com/watch?v=Cw2qD87KDHc',
    description: 'Gary Lewandowski explores the psychology behind betrayal and the path to recovery.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/Cw2qD87KDHc/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Nora McInerny We Don\'t Move On from Grief. We Move Forward with It'),
    title: 'We Don\'t Move On from Grief. We Move Forward with It',
    speakerName: 'Nora McInerny',
    tedUrl: 'https://www.ted.com/talks/nora_mcinerny_we_don_t_move_on_from_grief_we_move_forward_with_it',
    description: 'Nora McInerny shares her personal experience with grief and loss, showing how we can move forward while still carrying our grief.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/nora_mcinerny_we_don_t_move_on_from_grief_we_move_forward_with_it.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Andy Puddicombe All It Takes is 10 Mindful Minutes'),
    title: 'All It Takes is 10 Mindful Minutes',
    speakerName: 'Andy Puddicombe',
    tedUrl: 'https://www.ted.com/talks/andy_puddicombe_all_it_takes_is_10_mindful_minutes',
    description: 'Andy Puddicombe, founder of Headspace, shows how 10 mindful minutes can transform your life.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/andy_puddicombe_all_it_takes_is_10_mindful_minutes.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Margaret Heffernan The Dangers of \'Willful Blindness\''),
    title: 'The Dangers of \'Willful Blindness\'',
    speakerName: 'Margaret Heffernan',
    tedUrl: 'https://www.ted.com/talks/margaret_heffernan_the_dangers_of_willful_blindness',
    description: 'Margaret Heffernan examines the phenomenon of willful blindness and why we ignore the obvious at our peril.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/margaret_heffernan_the_dangers_of_willful_blindness.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Pamela Meyer How to Spot a Liar'),
    title: 'How to Spot a Liar',
    speakerName: 'Pamela Meyer',
    tedUrl: 'https://www.ted.com/talks/pamela_meyer_how_to_spot_a_liar',
    description: 'Pamela Meyer shows the manners and "hotspots" used by those trained to recognize deception.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/pamela_meyer_how_to_spot_a_liar.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Brené Brown Listening to Shame'),
    title: 'Listening to Shame',
    speakerName: 'Brené Brown',
    tedUrl: 'https://www.ted.com/talks/brene_brown_listening_to_shame',
    description: 'Brené Brown explores what can happen when people confront their shame head-on.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/brene_brown_listening_to_shame.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Steven Johnson Where Good Ideas Come From'),
    title: 'Where Good Ideas Come From',
    speakerName: 'Steven Johnson',
    tedUrl: 'https://www.ted.com/talks/steven_johnson_where_good_ideas_come_from',
    description: 'Steven Johnson explores the history of innovation and shares his theory about where good ideas come from.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/steven_johnson_where_good_ideas_come_from.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Tim Urban Inside the Mind of a Master Procrastinator'),
    title: 'Inside the Mind of a Master Procrastinator',
    speakerName: 'Tim Urban',
    tedUrl: 'https://www.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator',
    description: 'Tim Urban takes us on a journey through YouTube binges, Wikipedia rabbit holes and bouts of staring out the window.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/tim_urban_inside_the_mind_of_a_master_procrastinator.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Sam Harris Can We Build AI Without Losing Control Over It?'),
    title: 'Can We Build AI Without Losing Control Over It?',
    speakerName: 'Sam Harris',
    tedUrl: 'https://www.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it',
    description: 'Sam Harris confronts us with a question that may matter more than any in human history: Can we build AI without losing control over it?',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/sam_harris_can_we_build_ai_without_losing_control_over_it.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Gever Tulley 5 Dangerous Things You Should Let Your Kids Do'),
    title: '5 Dangerous Things You Should Let Your Kids Do',
    speakerName: 'Gever Tulley',
    tedUrl: 'https://www.youtube.com/watch?v=eIho2S0ZahI',
    description: 'Gever Tulley shares five dangerous things kids should be allowed to do -- and why a little danger is good.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/eIho2S0ZahI/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Michael Norton How to Buy Happiness'),
    title: 'How to Buy Happiness',
    speakerName: 'Michael Norton',
    tedUrl: 'https://www.ted.com/talks/michael_norton_how_to_buy_happiness',
    description: 'Michael Norton shares surprising research on how spending money on others can make you happier.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/michael_norton_how_to_buy_happiness.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Tom Wujec Build a Tower, Build a Team'),
    title: 'Build a Tower, Build a Team',
    speakerName: 'Tom Wujec',
    tedUrl: 'https://www.ted.com/talks/tom_wujec_build_a_tower_build_a_team',
    description: 'Tom Wujec presents surprising research about what makes teams work effectively through the Marshmallow Challenge.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/tom_wujec_build_a_tower_build_a_team.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('David Allen The Art of Stress-Free Productivity'),
    title: 'The Art of Stress-Free Productivity',
    speakerName: 'David Allen',
    tedUrl: 'https://www.ted.com/talks/david_allen_the_art_of_stress_free_productivity',
    description: 'David Allen, creator of Getting Things Done, shares his approach to stress-free productivity.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/david_allen_the_art_of_stress_free_productivity.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Mandy Len Catron A Better Way to Talk About Love'),
    title: 'A Better Way to Talk About Love',
    speakerName: 'Mandy Len Catron',
    tedUrl: 'https://www.ted.com/talks/mandy_len_catron_a_better_way_to_talk_about_love',
    description: 'Mandy Len Catron explores the language and metaphors we use to talk about love.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/mandy_len_catron_a_better_way_to_talk_about_love.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Al Vernacchio Sex Needs a New Metaphor. Here\'s One'),
    title: 'Sex Needs a New Metaphor. Here\'s One',
    speakerName: 'Al Vernacchio',
    tedUrl: 'https://www.ted.com/talks/al_vernacchio_sex_needs_a_new_metaphor_here_s_one',
    description: 'Al Vernacchio argues that our current metaphor for sex is broken and proposes a healthier alternative.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/al_vernacchio_sex_needs_a_new_metaphor_here_s_one.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Adam Grant The Surprising Habits of Original Thinkers'),
    title: 'The Surprising Habits of Original Thinkers',
    speakerName: 'Adam Grant',
    tedUrl: 'https://www.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers',
    description: 'Adam Grant explores the habits of original thinkers and shows that procrastination can be a virtue for creativity.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/adam_grant_the_surprising_habits_of_original_thinkers.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Peter Singer The Why and How of Effective Altruism'),
    title: 'The Why and How of Effective Altruism',
    speakerName: 'Peter Singer',
    tedUrl: 'https://www.ted.com/talks/peter_singer_the_why_and_how_of_effective_altruism',
    description: 'Peter Singer explores how we can find more meaning in our lives by helping others most effectively.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/peter_singer_the_why_and_how_of_effective_altruism.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Amy Gutmann What It Means to Be a Global Citizen'),
    title: 'What It Means to Be a Global Citizen',
    speakerName: 'Amy Gutmann',
    tedUrl: 'https://youtu.be/ZwGEQcFo9RE',
    description: 'Amy Gutmann explores what it means to be a global citizen in today\'s interconnected world.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/ZwGEQcFo9RE/hqdefault.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Paul Piff Does Money Make You Mean?'),
    title: 'Does Money Make You Mean?',
    speakerName: 'Paul Piff',
    tedUrl: 'https://www.ted.com/talks/paul_piff_does_money_make_you_mean',
    description: 'Paul Piff shares research that shows how wealth can make people less compassionate and more entitled.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/paul_piff_does_money_make_you_mean.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Bill Gross The Single Biggest Reason Why Startups Succeed'),
    title: 'The Single Biggest Reason Why Startups Succeed',
    speakerName: 'Bill Gross',
    tedUrl: 'https://www.ted.com/talks/bill_gross_the_single_biggest_reason_why_startups_succeed',
    description: 'Bill Gross reveals the single biggest reason why startups succeed after analyzing hundreds of companies.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/bill_gross_the_single_biggest_reason_why_startups_succeed.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Carol Dweck The Power of Believing That You Can Improve'),
    title: 'The Power of Believing That You Can Improve',
    speakerName: 'Carol Dweck',
    tedUrl: 'https://www.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve',
    description: 'Carol Dweck describes two ways to think about a problem that\'s slightly too hard for you to solve: growth mindset versus fixed mindset.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/carol_dweck_the_power_of_believing_that_you_can_improve.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Chip Conley What Baby Boomers Can Learn from Millennials at Work -- and Vice Versa'),
    title: 'What Baby Boomers Can Learn from Millennials at Work -- and Vice Versa',
    speakerName: 'Chip Conley',
    tedUrl: 'https://www.ted.com/talks/chip_conley_what_baby_boomers_can_learn_from_millennials_at_work_and_vice_versa',
    description: 'Chip Conley explores the mutual mentorship between different generations in the workplace.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/chip_conley_what_baby_boomers_can_learn_from_millennials_at_work_and_vice_versa.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Ray Dalio How to Build a Company Where the Best Ideas Win'),
    title: 'How to Build a Company Where the Best Ideas Win',
    speakerName: 'Ray Dalio',
    tedUrl: 'https://www.ted.com/talks/ray_dalio_how_to_build_a_company_where_the_best_ideas_win',
    description: 'Ray Dalio shares the unconventional principles he developed to create a culture of radical truth and transparency.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://embed-ssl.ted.com/talks/ray_dalio_how_to_build_a_company_where_the_best_ideas_win.jpg',
    language: 'en',
  },
  {
    slug: generateSlug('Laura Vanderkam How to Gain Control of Your Free Time'),
    title: 'How to Gain Control of Your Free Time',
    speakerName: 'Laura Vanderkam',
    tedUrl: 'https://youtu.be/gmj-azFbpkA',
    description: 'Laura Vanderkam shares practical strategies for making time for the things that matter most.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: 'https://img.youtube.com/vi/gmj-azFbpkA/hqdefault.jpg',
    language: 'en',
  }
];
