import { generateSlug } from './helpers';

// Unique TED talks extracted from CSV files
// Note: Some talks appear multiple times across different cards
export const talksSeedData = [
  {
    slug: generateSlug('Stuart Brown Play is More Than Just Fun'),
    title: 'Play is More Than Just Fun',
    speakerName: 'Stuart Brown',
    tedUrl: 'https://www.youtube.com/watch?v=cRC0Kvrn93Q',
    description: 'Stuart Brown says play is more than just joyful and energy-burning. It\'s deeply connected with innovation, adaptation, and resilience.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('David Blaine How I Held My Breath for 17 Minutes'),
    title: 'How I Held My Breath for 17 Minutes',
    speakerName: 'David Blaine',
    tedUrl: 'https://www.ted.com/talks/david_blaine_how_i_held_my_breath_for_17_minutes',
    description: 'David Blaine describes his journey to hold his breath underwater for 17 minutes.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Jill Bolte Taylor My Stroke of Insight'),
    title: 'My Stroke of Insight',
    speakerName: 'Jill Bolte Taylor',
    tedUrl: 'https://www.ted.com/talks/jill_bolte_taylor_my_stroke_of_insight',
    description: 'Jill Bolte Taylor got a research opportunity few brain scientists would wish for: She had a massive stroke, and watched as her brain functions shut down one by one.',
    durationSeconds: null,
    eventName: null,
    year: 2008,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Brené Brown The Power of Vulnerability'),
    title: 'The Power of Vulnerability',
    speakerName: 'Brené Brown',
    tedUrl: 'https://www.ted.com/talks/brene_brown_the_power_of_vulnerability',
    description: 'Brené Brown studies human connection -- our ability to empathize, belong, love.',
    durationSeconds: 1223,
    eventName: 'TEDxHouston',
    year: 2010,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Jonathan Haidt The Moral Roots of Liberals and Conservatives'),
    title: 'The Moral Roots of Liberals and Conservatives',
    speakerName: 'Jonathan Haidt',
    tedUrl: 'https://www.youtube.com/watch?v=9ei_HSlUxUQ',
    description: 'Jonathan Haidt studies the five moral values that form the basis of our political choices.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Angela Lee Duckworth Grit The Power of Passion and Perseverance'),
    title: 'Grit: The Power of Passion and Perseverance',
    speakerName: 'Angela Lee Duckworth',
    tedUrl: 'https://www.ted.com/talks/angela_lee_duckworth_grit_the_power_of_passion_and_perseverance',
    description: 'Angela Lee Duckworth explains her theory of "grit" as a predictor of success.',
    durationSeconds: 366,
    eventName: 'TED Talks Education',
    year: 2013,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Helen Fisher The Brain in Love'),
    title: 'The Brain in Love',
    speakerName: 'Helen Fisher',
    tedUrl: 'https://www.ted.com/talks/helen_fisher_the_brain_in_love',
    description: 'Helen Fisher takes on a tricky topic – love – and explains its evolution, its biochemical foundations and its social importance.',
    durationSeconds: null,
    eventName: null,
    year: 2008,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Simon Sinek Why Good Leaders Make You Feel Safe'),
    title: 'Why Good Leaders Make You Feel Safe',
    speakerName: 'Simon Sinek',
    tedUrl: 'https://www.ted.com/talks/simon_sinek_why_good_leaders_make_you_feel_safe',
    description: 'Simon Sinek explores how leaders can inspire cooperation, trust and change.',
    durationSeconds: 720,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Pico Iyer The Art of Stillness'),
    title: 'The Art of Stillness',
    speakerName: 'Pico Iyer',
    tedUrl: 'https://www.ted.com/talks/pico_iyer_the_art_of_stillness',
    description: 'Pico Iyer makes a case for taking time out of our lives to step into the beauty of stillness.',
    durationSeconds: 917,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Bryan Stevenson We Need to Talk About an Injustice'),
    title: 'We Need to Talk About an Injustice',
    speakerName: 'Bryan Stevenson',
    tedUrl: 'https://www.ted.com/talks/bryan_stevenson_we_need_to_talk_about_an_injustice',
    description: 'Bryan Stevenson presents the statistics and stories of our racially biased justice system.',
    durationSeconds: 1422,
    eventName: 'TED',
    year: 2012,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Amy Cuddy Your Body Language May Shape Who You Are'),
    title: 'Your Body Language May Shape Who You Are',
    speakerName: 'Amy Cuddy',
    tedUrl: 'https://youtu.be/NDQ1Mi5I4rg',
    description: 'Amy Cuddy shows how "power posing" can boost feelings of confidence.',
    durationSeconds: 1265,
    eventName: 'TEDGlobal',
    year: 2012,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Bill Gates The Next Outbreak We\'re Not Ready'),
    title: 'The Next Outbreak? We\'re Not Ready',
    speakerName: 'Bill Gates',
    tedUrl: 'https://www.ted.com/talks/bill_gates_the_next_outbreak_we_re_not_ready',
    description: 'Bill Gates explains why we should be more scared of a deadly epidemic than nuclear war.',
    durationSeconds: null,
    eventName: null,
    year: 2015,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Johann Hari Everything You Think You Know About Addiction is Wrong'),
    title: 'Everything You Think You Know About Addiction is Wrong',
    speakerName: 'Johann Hari',
    tedUrl: 'https://www.ted.com/talks/johann_hari_everything_you_think_you_know_about_addiction_is_wrong',
    description: 'Johann Hari argues that the real cure for addiction is social connection.',
    durationSeconds: 885,
    eventName: 'TEDGlobal',
    year: 2015,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Dan Buettner How to Live to Be 100+'),
    title: 'How to Live to Be 100+',
    speakerName: 'Dan Buettner',
    tedUrl: 'https://www.ted.com/talks/dan_buettner_how_to_live_to_be_100',
    description: 'Dan Buettner reveals 9 common diet and lifestyle habits that keep them spry past age 100.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('BJ Miller What Really Matters at the End of Life'),
    title: 'What Really Matters at the End of Life',
    speakerName: 'BJ Miller',
    tedUrl: 'https://www.ted.com/talks/bj_miller_what_really_matters_at_the_end_of_life',
    description: 'BJ Miller asks: What really matters at the end of life?',
    durationSeconds: 1146,
    eventName: 'TEDMED',
    year: 2015,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Loftus How Reliable is Your Memory'),
    title: 'How Reliable is Your Memory',
    speakerName: 'Elizabeth Loftus',
    tedUrl: 'https://www.ted.com/talks/elizabeth_loftus_how_reliable_is_your_memory',
    description: 'Elizabeth Loftus studies false memories and explains how easy it is to manipulate memory.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Caroline Casey Looking Past Limits'),
    title: 'Looking Past Limits',
    speakerName: 'Caroline Casey',
    tedUrl: 'https://www.ted.com/talks/caroline_casey_looking_past_limits',
    description: 'Caroline Casey tells about her journey beyond limits.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Sam Berns My Philosophy for a Happy Life'),
    title: 'My Philosophy for a Happy Life',
    speakerName: 'Sam Berns',
    tedUrl: 'https://www.ted.com/talks/sam_berns_my_philosophy_for_a_happy_life',
    description: 'Sam Berns shares his philosophy for a happy life.',
    durationSeconds: 758,
    eventName: 'TEDxMidAtlantic',
    year: 2013,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Success Failure and the Drive to Keep Creating'),
    title: 'Success, Failure, and the Drive to Keep Creating',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_success_failure_and_the_drive_to_keep_creating',
    description: 'Elizabeth Gilbert reflects on the complexities of creativity and inspiration.',
    durationSeconds: 1096,
    eventName: 'TED',
    year: 2014,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Shawn Achor The Happy Secret to Better Work'),
    title: 'The Happy Secret to Better Work',
    speakerName: 'Shawn Achor',
    tedUrl: 'https://www.ted.com/talks/shawn_achor_the_happy_secret_to_better_work',
    description: 'Shawn Achor argues that happiness inspires productivity.',
    durationSeconds: 744,
    eventName: 'TEDxBloomington',
    year: 2011,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Beau Lotto Optical Illusions Show How We See'),
    title: 'Optical Illusions Show How We See',
    speakerName: 'Beau Lotto',
    tedUrl: 'https://www.ted.com/talks/beau_lotto_optical_illusions_show_how_we_see',
    description: 'Beau Lotto explains how perception shapes our understanding of the world.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Elizabeth Gilbert Your Elusive Creative Genius'),
    title: 'Your Elusive Creative Genius',
    speakerName: 'Elizabeth Gilbert',
    tedUrl: 'https://www.ted.com/talks/elizabeth_gilbert_your_elusive_creative_genius',
    description: 'Elizabeth Gilbert muses on the impossible things we expect from artists and geniuses.',
    durationSeconds: 1145,
    eventName: 'TED',
    year: 2009,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Hannah Fry The Mathematics of Love'),
    title: 'The Mathematics of Love',
    speakerName: 'Hannah Fry',
    tedUrl: 'https://www.ted.com/talks/hannah_fry_the_mathematics_of_love',
    description: 'Hannah Fry explores the mathematical patterns in human behavior.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Carla Harris How to Find the Person Who Can Help You Get Ahead at Work'),
    title: 'How to Find the Person Who Can Help You Get Ahead at Work',
    speakerName: 'Carla Harris',
    tedUrl: 'https://www.ted.com/talks/carla_harris_how_to_find_the_person_who_can_help_you_get_ahead_at_work',
    description: 'Carla Harris explains the difference between a sponsor and a mentor.',
    durationSeconds: null,
    eventName: null,
    year: null,
    thumbnailUrl: null,
    language: 'en',
  },
  {
    slug: generateSlug('Robert Waldinger What Makes a Good Life Lessons from the Longest Study on Happiness'),
    title: 'What Makes a Good Life? Lessons from the Longest Study on Happiness',
    speakerName: 'Robert Waldinger',
    tedUrl: 'https://www.youtube.com/watch?v=HSercnrqeN4',
    description: 'Robert Waldinger shares lessons from a 75-year study on happiness.',
    durationSeconds: 770,
    eventName: 'TEDxBeaconStreet',
    year: 2015,
    thumbnailUrl: null,
    language: 'en',
  },
  // Additional talks to be added as needed
];
